// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5352a114c0b2f653 "Pepper (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default, stdin_default2 } from "../chunks/chunk-S6JKNUE6.js";
import "../chunks/chunk-QSX6W3S5.js";
import "../chunks/chunk-D7Q3IFKZ.js";
import "../chunks/chunk-JEA7JOIB.js";
import "../chunks/chunk-YSF7EGQK.js";
import "../chunks/chunk-LCYZNAAJ.js";
import "../chunks/chunk-TEXBX6PP.js";
import { routes } from "../chunks/chunk-H6F5WHVF.js";

// virtual:reviews/slideshow-reviews
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8A6lNQlVRixJjM1o3K18/GfUhWVXBDDh9eYpDVVn1/qIfR3dYEn.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	forwardLoader,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ReviewsReviewCardFonts = getFonts(stdin_default2);
var SlideshowFonts = getFonts(stdin_default);
var serializationHash = "framer-V70ca";
var variantClassNames = {
	bSPGPlhqo: "framer-v-17nuwbn",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "bSPGPlhqo",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-17nuwbn",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"bSPGPlhqo"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 24,
							borderBottomRightRadius: 24,
							borderTopLeftRadius: 24,
							borderTopRightRadius: 24,
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1lxcodh-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"ZVFF84uFI-container"}
								nodeId={"ZVFF84uFI"}
								rendersWithMotion={true}
								scopeId={"qIfR3dYEn"}
							>
								{_jsx(stdin_default, {
									alignment: "center",
									arrowOptions: {
										arrowFill: "rgba(0, 0, 0, 0.2)",
										arrowGap: 10,
										arrowPadding: 24,
										arrowPaddingBottom: 0,
										arrowPaddingLeft: 0,
										arrowPaddingRight: 0,
										arrowPaddingTop: 0,
										arrowPosition: "auto",
										arrowRadius: 40,
										arrowShouldFadeIn: false,
										arrowShouldSpace: true,
										arrowSize: 36,
										showMouseControls: true,
									},
									autoPlayControl: true,
									borderRadius: 0,
									direction: "left",
									dragControl: true,
									effectsOptions: {
										effectsHover: false,
										effectsOpacity: 0.2,
										effectsPerspective: 1200,
										effectsRotate: 0,
										effectsScale: 1,
										playOffscreen: false,
									},
									fadeOptions: {
										fadeAlpha: 0,
										fadeContent: false,
										fadeInset: 0,
										fadeWidth: 25,
										overflow: true,
									},
									gap: 24,
									height: "100%",
									id: "ZVFF84uFI",
									intervalControl: 10,
									itemAmount: 1,
									layoutId: "ZVFF84uFI",
									padding: 0,
									paddingBottom: 0,
									paddingLeft: 0,
									paddingPerSide: false,
									paddingRight: 0,
									paddingTop: 0,
									progressOptions: {
										dotsActiveOpacity: 1,
										dotsBackground: "rgba(0, 0, 0, 0.2)",
										dotsBlur: 0,
										dotsFill: "rgb(255, 255, 255)",
										dotsGap: 10,
										dotsInset: 10,
										dotSize: 10,
										dotsOpacity: 0.5,
										dotsPadding: 10,
										dotsRadius: 50,
										showProgressDots: false,
									},
									slots: [
										<ComponentViewportProvider height={615} width={"538px"}>
											<SmartComponentScopedContainer
												className={"framer-7pjq93-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"KkUI9UmtI-container"}
												nodeId={"KkUI9UmtI"}
												rendersWithMotion={true}
												scopeId={"qIfR3dYEn"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "KkUI9UmtI",
													layoutId: "KkUI9UmtI",
													Lk63OzDI8: addImageAlt(
														{
															pixelHeight: 1344,
															pixelWidth: 896,
															src: "https://framerusercontent.com/images/pebU74xcJF0VEsgm3JfH7G6NYAQ.png?width=896&height=1344",
															srcSet:
																"https://framerusercontent.com/images/pebU74xcJF0VEsgm3JfH7G6NYAQ.png?scale-down-to=1024&width=896&height=1344 682w,https://framerusercontent.com/images/pebU74xcJF0VEsgm3JfH7G6NYAQ.png?width=896&height=1344 896w",
														},
														"Chef Marco Di Luca",
													),
													Mda0lIURA: "Chef Marco Di Luca",
													OWCd7GSmm:
														"Executive Chef, Trattoria La Bella (New York)",
													style: {
														height: "100%",
														width: "100%",
													},
													TcDdmd4iG: (
														<React.Fragment>
															<p>
																{
																	"\u201CThe balance of flavors in their Truffle Temptation pizza is simply divine. It\u2019s a perfect example of how simplicity, when done right, can create an unforgettable culinary experience.\u201D"
																}
															</p>
														</React.Fragment>
													),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={615} width={"538px"}>
											<SmartComponentScopedContainer
												className={"framer-bahnh9-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"AKNKrT4E6-container"}
												nodeId={"AKNKrT4E6"}
												rendersWithMotion={true}
												scopeId={"qIfR3dYEn"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "AKNKrT4E6",
													layoutId: "AKNKrT4E6",
													Lk63OzDI8: addImageAlt(
														{
															pixelHeight: 1312,
															pixelWidth: 896,
															src: "https://framerusercontent.com/images/cJlMf5sDtI0CbOfCJQMyUerrZWc.png?width=896&height=1312",
															srcSet:
																"https://framerusercontent.com/images/cJlMf5sDtI0CbOfCJQMyUerrZWc.png?scale-down-to=1024&width=896&height=1312 699w,https://framerusercontent.com/images/cJlMf5sDtI0CbOfCJQMyUerrZWc.png?width=896&height=1312 896w",
														},
														"Emma Gallagher",
													),
													Mda0lIURA: "Emma Gallagher",
													OWCd7GSmm: "Senior Food Writer, London Eats Magazine",
													style: {
														height: "100%",
														width: "100%",
													},
													TcDdmd4iG: (
														<React.Fragment>
															<p>
																{
																	"\u201CWith fresh ingredients and bold flavors, this pizzeria redefines what fast-casual pizza can be. Their BBQ Blaze is a must-try for anyone who loves the perfect mix of sweet and smoky.\u201D"
																}
															</p>
														</React.Fragment>
													),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={615} width={"538px"}>
											<SmartComponentScopedContainer
												className={"framer-1wytoyy-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"WVERIZNjK-container"}
												nodeId={"WVERIZNjK"}
												rendersWithMotion={true}
												scopeId={"qIfR3dYEn"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "WVERIZNjK",
													layoutId: "WVERIZNjK",
													Lk63OzDI8: addImageAlt(
														{
															pixelHeight: 1344,
															pixelWidth: 896,
															positionX: "50%",
															positionY: "50%",
															src: "https://framerusercontent.com/images/th2iELXOzEME2cqduvrTZtJsM.png?width=896&height=1344",
															srcSet:
																"https://framerusercontent.com/images/th2iELXOzEME2cqduvrTZtJsM.png?scale-down-to=1024&width=896&height=1344 682w,https://framerusercontent.com/images/th2iELXOzEME2cqduvrTZtJsM.png?width=896&height=1344 896w",
														},
														"Lucas van den Berg",
													),
													Mda0lIURA: "Lucas van den Berg",
													OWCd7GSmm:
														"Restaurant Critic, The Amsterdam Culinary Journal",
													style: {
														height: "100%",
														width: "100%",
													},
													TcDdmd4iG: (
														<React.Fragment>
															<p>
																{
																	"\u201CTheir Mediterranean Marvel pizza took me straight to the coast of Greece. It\u2019s clear they\u2019re passionate about quality and authenticity, with every bite delivering a burst of vibrant, fresh ingredients.\u201D"
																}
															</p>
														</React.Fragment>
													),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={615} width={"538px"}>
											<SmartComponentScopedContainer
												className={"framer-13wlk94-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"rZJAK6_As-container"}
												nodeId={"rZJAK6_As"}
												rendersWithMotion={true}
												scopeId={"qIfR3dYEn"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "rZJAK6_As",
													layoutId: "rZJAK6_As",
													Lk63OzDI8: addImageAlt(
														{
															pixelHeight: 1344,
															pixelWidth: 896,
															src: "https://framerusercontent.com/images/kkPG2fhb0mhNAuKO3iShcfcA3s.png?width=896&height=1344",
															srcSet:
																"https://framerusercontent.com/images/kkPG2fhb0mhNAuKO3iShcfcA3s.png?scale-down-to=1024&width=896&height=1344 682w,https://framerusercontent.com/images/kkPG2fhb0mhNAuKO3iShcfcA3s.png?width=896&height=1344 896w",
														},
														"Sophie Jensen",
													),
													Mda0lIURA: "Sophie Jensen",
													OWCd7GSmm: "Head of Culinary Arts, Gourmet Institute",
													style: {
														height: "100%",
														width: "100%",
													},
													TcDdmd4iG: (
														<React.Fragment>
															<p>
																{
																	"\u201CFew places combine traditional pizza-making techniques with modern creativity so effortlessly. The Garlic Supreme is a prime example of innovation in comfort food.\u201D"
																}
															</p>
														</React.Fragment>
													),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={615} width={"538px"}>
											<SmartComponentScopedContainer
												className={"framer-1yybqk3-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"u72mvsCZJ-container"}
												nodeId={"u72mvsCZJ"}
												rendersWithMotion={true}
												scopeId={"qIfR3dYEn"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "u72mvsCZJ",
													layoutId: "u72mvsCZJ",
													Lk63OzDI8: addImageAlt(
														{
															pixelHeight: 1344,
															pixelWidth: 896,
															src: "https://framerusercontent.com/images/tRpVH2v58wxByRcqFLIcTnQZM.png?width=896&height=1344",
															srcSet:
																"https://framerusercontent.com/images/tRpVH2v58wxByRcqFLIcTnQZM.png?scale-down-to=1024&width=896&height=1344 682w,https://framerusercontent.com/images/tRpVH2v58wxByRcqFLIcTnQZM.png?width=896&height=1344 896w",
														},
														"Maximilian Schneider",
													),
													Mda0lIURA: "Maximilian Schneider",
													OWCd7GSmm: "Food Blogger, Berlin Bites",
													style: {
														height: "100%",
														width: "100%",
													},
													TcDdmd4iG: (
														<React.Fragment>
															<p>
																{
																	"\u201CThe Meat Lover's Feast is everything a carnivore dreams of, loaded with perfectly cooked meats and balanced with just the right amount of sauce. This is pizza at its finest.\u201D"
																}
															</p>
														</React.Fragment>
													),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={615} width={"538px"}>
											<SmartComponentScopedContainer
												className={"framer-ulj82g-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"kSCmOMxrR-container"}
												nodeId={"kSCmOMxrR"}
												rendersWithMotion={true}
												scopeId={"qIfR3dYEn"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "kSCmOMxrR",
													layoutId: "kSCmOMxrR",
													Lk63OzDI8: addImageAlt(
														{
															pixelHeight: 1344,
															pixelWidth: 896,
															src: "https://framerusercontent.com/images/1sTKk5XcAglkinbs8sX8Vw9FSDg.png?width=896&height=1344",
															srcSet:
																"https://framerusercontent.com/images/1sTKk5XcAglkinbs8sX8Vw9FSDg.png?scale-down-to=1024&width=896&height=1344 682w,https://framerusercontent.com/images/1sTKk5XcAglkinbs8sX8Vw9FSDg.png?width=896&height=1344 896w",
														},
														"Andreea Dumitrescu",
													),
													Mda0lIURA: "Andreea Dumitrescu",
													OWCd7GSmm: "Editor-in-Chief, Bucharest Foodie",
													style: {
														height: "100%",
														width: "100%",
													},
													TcDdmd4iG: (
														<React.Fragment>
															<p>
																{
																	"\u201CIn a city full of pizza joints, this place stands out. Their Firecracker Inferno brings the perfect level of spice without overwhelming the flavor. It\u2019s a true gem in the heart of Bucharest.\u201D"
																}
															</p>
														</React.Fragment>
													),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
									],
									startFrom: 0,
									style: {
										height: "100%",
										width: "100%",
									},
									transitionControl: {
										damping: 40,
										delay: 0,
										mass: 1,
										stiffness: 200,
										type: "spring",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-V70ca.framer-1t0qnp0, .framer-V70ca .framer-1t0qnp0 { display: block; }",
	".framer-V70ca.framer-17nuwbn { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 659px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 552px; }",
	".framer-V70ca .framer-1lxcodh-container { flex: 1 0 0px; height: 1px; position: relative; width: 100%; }",
	".framer-V70ca .framer-7pjq93-container, .framer-V70ca .framer-bahnh9-container, .framer-V70ca .framer-1wytoyy-container, .framer-V70ca .framer-13wlk94-container, .framer-V70ca .framer-1yybqk3-container, .framer-V70ca .framer-ulj82g-container { height: 615px; position: relative; width: 538px; }",
];
var FramerqIfR3dYEn = withCSS(Component, css, "framer-V70ca");
var stdin_default3 = FramerqIfR3dYEn;
FramerqIfR3dYEn.displayName = "Reviews/Slideshow - Reviews";
FramerqIfR3dYEn.defaultProps = {
	height: 659,
	width: 552,
};
addFonts(
	FramerqIfR3dYEn,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ReviewsReviewCardFonts,
		...SlideshowFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerqIfR3dYEn.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default2, {}, context)]);
	},
};

// virtual:reviews/slideshow-reviews
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5352a114c0b2f6533408ce29eda21dd74155cc4d0edaebe1b159ba55a597a9fd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SlideshowReviewsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5352a114c0b2f6533408ce29eda21dd74155cc4d0edaebe1b159ba55a597a9fd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var slideshow_reviews_default = ComponentWithRoot;
export { slideshow_reviews_default as default };
