// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5352a114c0b2f653 "Pepper (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-HLWZXJZG.js";
import { routes } from "./chunks/chunk-H6F5WHVF.js";

// virtual:contact-form
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/5FFoEDd2SNNjgggXWMp8/kkYcrwC1qiJKXfIyTf9w/bASbvVKJi.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	FormContainer,
	FormPlainTextInput,
	forwardLoader,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ButtonFormFonts = getFonts(stdin_default);
var cycleOrder = ["hF7xvMTgA", "n7N1GV0re"];
var serializationHash = "framer-xBf0y";
var variantClassNames = {
	hF7xvMTgA: "framer-v-1fxvk0j",
	n7N1GV0re: "framer-v-2t40rk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var formVariants = (form, variants, currentVariant) => {
	switch (form.state) {
		case "success":
			return variants.success ?? currentVariant;
		case "pending":
			return variants.pending ?? currentVariant;
		case "error":
			return variants.error ?? currentVariant;
		case "incomplete":
			return variants.incomplete ?? currentVariant;
		default:
			return currentVariant;
	}
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "hF7xvMTgA",
	Mobile: "n7N1GV0re",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "hF7xvMTgA",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "hF7xvMTgA",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<FormContainer
						{...restProps}
						{...gestureHandlers}
						action={
							"https://api.framer.com/forms/v1/forms/9dd8a3a6-a503-4503-afc2-474ffa5b3f07/submit"
						}
						className={cx(
							scopingClassNames,
							"framer-1fxvk0j",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"hF7xvMTgA"}
						nodeId={"hF7xvMTgA"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								n7N1GV0re: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{(formState) => (
							<_Fragment>
								<motion.label
									className={"framer-1rutbki"}
									data-framer-name={"Name"}
									layoutDependency={layoutDependency}
									layoutId={"gXc7rbo8Y"}
								>
									<FormPlainTextInput
										className={"framer-1flzhvb"}
										inputName={"Name"}
										layoutDependency={layoutDependency}
										layoutId={"rCevaNpvb"}
										placeholder={"Full Name"}
										required={true}
										style={{
											"--framer-input-background":
												"var(--token-e63bc84a-87bd-415d-9b16-445dc312962c, rgb(250, 250, 250))",
											"--framer-input-border-bottom-width": "1px",
											"--framer-input-border-color": "rgba(136, 136, 136, 0.1)",
											"--framer-input-border-left-width": "1px",
											"--framer-input-border-radius-bottom-left": "24px",
											"--framer-input-border-radius-bottom-right": "24px",
											"--framer-input-border-radius-top-left": "24px",
											"--framer-input-border-radius-top-right": "24px",
											"--framer-input-border-right-width": "1px",
											"--framer-input-border-style": "solid",
											"--framer-input-border-top-width": "1px",
											"--framer-input-font-color":
												"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51))",
											"--framer-input-icon-color": "rgb(153, 153, 153)",
											"--framer-input-placeholder-color":
												"var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128))",
										}}
										type={"text"}
									/>
								</motion.label>
								<motion.div
									className={"framer-bnlvtb"}
									layoutDependency={layoutDependency}
									layoutId={"h1zQIlBdK"}
								>
									<motion.label
										className={"framer-1xh9llx"}
										data-framer-name={"Email"}
										layoutDependency={layoutDependency}
										layoutId={"OMcU5GgYR"}
									>
										<FormPlainTextInput
											className={"framer-15k0wtq"}
											inputName={"Email"}
											layoutDependency={layoutDependency}
											layoutId={"mTqp5c5WY"}
											placeholder={"youremail@email.com"}
											required={true}
											style={{
												"--framer-input-background":
													"var(--token-e63bc84a-87bd-415d-9b16-445dc312962c, rgb(250, 250, 250))",
												"--framer-input-border-bottom-width": "1px",
												"--framer-input-border-color":
													"rgba(136, 136, 136, 0.1)",
												"--framer-input-border-left-width": "1px",
												"--framer-input-border-radius-bottom-left": "24px",
												"--framer-input-border-radius-bottom-right": "24px",
												"--framer-input-border-radius-top-left": "24px",
												"--framer-input-border-radius-top-right": "24px",
												"--framer-input-border-right-width": "1px",
												"--framer-input-border-style": "solid",
												"--framer-input-border-top-width": "1px",
												"--framer-input-font-color":
													"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51))",
												"--framer-input-icon-color": "rgb(153, 153, 153)",
												"--framer-input-placeholder-color":
													"var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128))",
											}}
											type={"email"}
										/>
									</motion.label>
									<motion.label
										className={"framer-tw6x4z"}
										data-framer-name={"Phone"}
										layoutDependency={layoutDependency}
										layoutId={"UK9iAO7FC"}
									>
										<FormPlainTextInput
											className={"framer-cojzf1"}
											inputName={"Phone"}
											layoutDependency={layoutDependency}
											layoutId={"sCNR12GcA"}
											placeholder={"+01 000 999 555"}
											required={true}
											style={{
												"--framer-input-background":
													"var(--token-e63bc84a-87bd-415d-9b16-445dc312962c, rgb(250, 250, 250))",
												"--framer-input-border-bottom-width": "1px",
												"--framer-input-border-color":
													"rgba(136, 136, 136, 0.1)",
												"--framer-input-border-left-width": "1px",
												"--framer-input-border-radius-bottom-left": "24px",
												"--framer-input-border-radius-bottom-right": "24px",
												"--framer-input-border-radius-top-left": "24px",
												"--framer-input-border-radius-top-right": "24px",
												"--framer-input-border-right-width": "1px",
												"--framer-input-border-style": "solid",
												"--framer-input-border-top-width": "1px",
												"--framer-input-font-color":
													"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51))",
												"--framer-input-icon-color": "rgb(153, 153, 153)",
												"--framer-input-placeholder-color":
													"var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128))",
											}}
											type={"tel"}
										/>
									</motion.label>
								</motion.div>
								<motion.label
									className={"framer-tbgeii"}
									data-framer-name={"Message"}
									layoutDependency={layoutDependency}
									layoutId={"Ax6IPkHJK"}
								>
									<FormPlainTextInput
										className={"framer-swljio"}
										inputName={"Message"}
										layoutDependency={layoutDependency}
										layoutId={"Tfn5HbLKv"}
										placeholder={"Type your message"}
										required={true}
										style={{
											"--framer-input-background":
												"var(--token-e63bc84a-87bd-415d-9b16-445dc312962c, rgb(250, 250, 250))",
											"--framer-input-border-bottom-width": "1px",
											"--framer-input-border-color": "rgba(136, 136, 136, 0.1)",
											"--framer-input-border-left-width": "1px",
											"--framer-input-border-radius-bottom-left": "24px",
											"--framer-input-border-radius-bottom-right": "24px",
											"--framer-input-border-radius-top-left": "24px",
											"--framer-input-border-radius-top-right": "24px",
											"--framer-input-border-right-width": "1px",
											"--framer-input-border-style": "solid",
											"--framer-input-border-top-width": "1px",
											"--framer-input-font-color":
												"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51))",
											"--framer-input-icon-color": "rgb(153, 153, 153)",
											"--framer-input-placeholder-color":
												"var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128))",
										}}
										type={"textarea"}
									/>
								</motion.label>
								<ComponentViewportProvider height={48}>
									<SmartComponentScopedContainer
										className={"framer-xe9tjc-container"}
										layoutDependency={layoutDependency}
										layoutId={"lsTi0ccSW-container"}
										nodeId={"lsTi0ccSW"}
										rendersWithMotion={true}
										scopeId={"bASbvVKJi"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "lsTi0ccSW",
											layoutId: "lsTi0ccSW",
											type: "submit",
											variant: formVariants(
												formState,
												{
													pending: "UUDmxBpbn",
													success: "edoZVqWvl",
												},
												matchVariant("nYLI2tEax"),
											),
											width: "100%",
											Zej6Dkc0D: "Send Message",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</_Fragment>
						)}
					</FormContainer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xBf0y.framer-zrcu7f, .framer-xBf0y .framer-zrcu7f { display: block; }",
	".framer-xBf0y.framer-1fxvk0j { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 564px; }",
	".framer-xBf0y .framer-1rutbki, .framer-xBf0y .framer-tbgeii { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	'.framer-xBf0y .framer-1flzhvb, .framer-xBf0y .framer-15k0wtq, .framer-xBf0y .framer-cojzf1 { --framer-input-focused-border-color: var(--token-7e4c7b4f-c1ce-4b49-afda-09aa102c67c0, #0080ff); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "Inter"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 14px; --framer-input-font-weight: 400; --framer-input-padding: 20px; flex: none; height: 48px; position: relative; width: 100%; }',
	".framer-xBf0y .framer-bnlvtb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-xBf0y .framer-1xh9llx, .framer-xBf0y .framer-tw6x4z { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1px; }",
	'.framer-xBf0y .framer-swljio { --framer-input-focused-border-color: var(--token-7e4c7b4f-c1ce-4b49-afda-09aa102c67c0, #0080ff); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "Inter"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 14px; --framer-input-font-weight: 400; --framer-input-padding: 20px; --framer-input-wrapper-height: auto; --framer-textarea-resize: vertical; flex: none; height: auto; min-height: 240px; position: relative; width: 100%; }',
	".framer-xBf0y .framer-xe9tjc-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-xBf0y.framer-v-2t40rk .framer-bnlvtb { flex-direction: column; }",
	".framer-xBf0y.framer-v-2t40rk .framer-1xh9llx, .framer-xBf0y.framer-v-2t40rk .framer-tw6x4z { flex: none; width: 100%; }",
];
var FramerbASbvVKJi = withCSS(Component, css, "framer-xBf0y");
var stdin_default2 = FramerbASbvVKJi;
FramerbASbvVKJi.displayName = "Contact Form";
FramerbASbvVKJi.defaultProps = {
	height: 200,
	width: 564,
};
addPropertyControls(FramerbASbvVKJi, {
	variant: {
		options: ["hF7xvMTgA", "n7N1GV0re"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerbASbvVKJi,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "google",
					style: "normal",
					uiFamilyName: "Inter",
					url: "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuLyfMZ1rib2Bg-4.woff2",
					weight: "400",
				},
			],
		},
		...ButtonFormFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerbASbvVKJi.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:contact-form
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "n7N1GV0re",
	xl: "hF7xvMTgA",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5352a114c0b2f6533408ce29eda21dd74155cc4d0edaebe1b159ba55a597a9fd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ContactFormFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5352a114c0b2f6533408ce29eda21dd74155cc4d0edaebe1b159ba55a597a9fd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var contact_form_default = ComponentWithRoot;
export { contact_form_default as default };
