-- public.profiles
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('03b2adc5-d064-4c66-8399-ee7bc4722cfc', 'Joseph Kolo', '', 'https://lh3.googleusercontent.com/a/ACg8ocLDmHn2uMsspCkumcxOxxYqxRMzHvLdx1MMowhFqSOV_Gtw8vz63A=s96-c', '2026-06-26 21:05:05.762827+00', '2026-06-26 21:05:05.762827+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('1a9af390-6f70-46b3-af71-f1afa582006a', 'siphesihle dabula', '', 'https://lh3.googleusercontent.com/a/ACg8ocJOBfHKsStzGz5IM9N-UJwBCNVGHkNg-Dgj3Ni9yQiJhb9AtcAJ=s96-c', '2026-07-04 16:26:31.848232+00', '2026-07-04 16:26:31.848232+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('2a8e3beb-36d6-4e81-9f65-da1ba6e0303e', 'noxolo victoria Cacambile', '', 'https://lh3.googleusercontent.com/a/ACg8ocIy2MbZLscOmHMumspVCgs6QzKbyv4b3UPR4iKtqJAMvMO99wC_Jg=s96-c', '2026-06-24 07:28:49.329252+00', '2026-06-24 07:28:49.329252+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('3bd38ea6-5900-4385-b34e-791c10231193', 'sisanda sigaba', '', 'https://lh3.googleusercontent.com/a/ACg8ocK_t4jYlsts3IjcCDkkQ3yZ2Bc_nirG3shdX-b9mB9uaVytvqP6=s96-c', '2026-06-10 14:14:33.489126+00', '2026-06-10 14:14:33.489126+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('4573516a-2e2f-45f6-85e9-7cd1508703ee', 'Nwabisa Cacambile', '+27621599554', '', '2026-06-23 17:59:18.479624+00', '2026-06-23 17:59:18.479624+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('8abcfa78-20ea-4906-9bfc-2e859097a957', 'Esona Madubedube', '', 'https://lh3.googleusercontent.com/a/ACg8ocKI7Y60g5zvU6Z-tM7D5BqK6auF_Zu4EkvSvkqeJkYeI2_3Cg=s96-c', '2026-07-12 20:51:18.71582+00', '2026-07-12 20:51:18.71582+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('9841c4b9-0499-42b0-88e1-c0ba653eab52', 'Bongani Cacambile', '+27747314959', '', '2026-06-08 21:48:06.20756+00', '2026-06-08 21:48:06.20756+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('a1585de3-becb-4c9d-bf27-eb01f2310136', 'Platform Admin', '', '', '2026-06-08 23:51:43.710443+00', '2026-06-08 23:51:43.710443+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('cabe86b7-0305-4ba8-a65f-4f6d867a4ac8', 'Simphiwe Ndongeni', '', 'https://lh3.googleusercontent.com/a/ACg8ocIu32GfGNp5NNGGjYe4voR6PbsxQ9t9ftPq8wJwiTbiGUOvLQ=s96-c', '2026-07-11 13:23:43.255788+00', '2026-07-11 13:23:43.255788+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('cecb8ea7-ddc1-4429-9472-165fac1e6d86', 'Lukhanyo Litye', '', 'https://lh3.googleusercontent.com/a/ACg8ocLksyEMiDeizLdIYxror0AG2XfYnDIhMFC2r_TQJxNA8n5-JCRFgg=s96-c', '2026-06-23 18:10:29.368756+00', '2026-06-23 18:10:29.368756+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('dd6cf6bb-cad5-489a-b3ed-984df8ac9cb2', 'sandile Sojiji', '', 'https://lh3.googleusercontent.com/a/ACg8ocKQkoHPeA4mSWtALDjeygdDi9OEI6M-B8ubjpAW_XfWL5oYow=s96-c', '2026-06-25 18:43:20.192921+00', '2026-06-25 18:43:20.192921+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('e020e4de-bd97-4c6d-a232-86a3877e699b', 'Caroline', '0797905791', '', '2026-06-20 17:32:06.210836+00', '2026-06-20 17:32:06.210836+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('e3276536-6a00-4f42-aae3-5e0d70ee96b1', 'Thozamile Mbalo', '', 'https://lh3.googleusercontent.com/a/ACg8ocKxGT4sr8O43L73m8CQiPPzrmNenGrELU3FGKecIGoQdH76Fvkt=s96-c', '2026-06-24 08:04:13.464426+00', '2026-06-24 08:04:13.464426+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('ecc6f15a-2531-47f4-aab9-e9c82646d769', 'Sonwabile Cacambile', '', 'https://lh3.googleusercontent.com/a/ACg8ocKqPsy4_SV78jV8eMlT5l6-27CbKlWmHoPSCjSAioirgYIyiA=s96-c', '2026-06-09 17:02:11.32223+00', '2026-06-09 17:02:11.32223+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');
INSERT INTO public."profiles" ("id", "full_name", "phone", "avatar_url", "created_at", "updated_at", "locale", "theme", "marketing_opt_in", "notification_prefs") VALUES ('f3f321bf-3621-40d3-b16a-91b58fc50a32', 'Nokuthula Sigaba', '', '', '2026-06-10 18:51:51.874747+00', '2026-06-10 18:51:51.874747+00', 'en', 'system', false, '{"sms": {"orders": false, "account": false, "security": true, "promotions": false}, "push": {"orders": true, "account": true, "security": true, "promotions": false}, "email": {"orders": true, "account": true, "security": true, "promotions": false}}');

-- public.products
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('alfredo-bliss', 'Creamy Alfredo Bliss', 'Fettuccine, butter, cream, Parmesan, black pepper, parsley', 129.90, 'pasta', 'https://framerusercontent.com/images/7WJgsBXCnl7ov0Uhe1ZthASTgQc.png', 'Dairy, Gluten, Eggs', 'Calories: 780 · Fat: 48g · Carbs: 72g · Protein: 18g', NULL, true, 50, '2026-06-08 23:07:53.87796+00', '2026-06-23 18:43:39.073389+00', 30, 5, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('apple-crumble', 'Warm Cinnamon Apple Crumble', 'Apples, cinnamon, oats, brown sugar, butter, flour, vanilla ice cream', 6.49, 'deserts', 'https://framerusercontent.com/images/QlVQ0YNHzBhb2nPfKPz2btr7A.png', 'Dairy, Gluten', 'Calories: 430 · Fat: 18g · Carbs: 64g · Protein: 5g', NULL, true, 10, '2026-06-15 21:55:47.517387+00', '2026-06-18 00:10:46.313576+00', 49, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('baked-ziti', 'Cheesy Baked Ziti', 'Penne, marinara, ricotta, mozzarella, Parmesan, baked golden', 13.49, 'pasta', 'https://framerusercontent.com/images/yNtyemqpPEBb8vP6SUEqoTsd74.png', 'Dairy, Gluten', 'Calories: 850 · Fat: 40g · Carbs: 86g · Protein: 34g', NULL, true, 20, '2026-06-15 21:55:47.517387+00', '2026-06-15 21:55:47.517387+00', 50, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('bbq-blaze', 'BBQ Blaze', 'Grilled chicken, red onions, smoky BBQ sauce, cheddar, mozzarella, cilantro', 80.00, 'pizza', 'https://framerusercontent.com/images/dQKnVrygQTPBTqZDioB8akNs.png', 'Dairy, Gluten', 'Calories: 290 · Fat: 12g · Carbs: 29g · Protein: 15g', 'from', false, 80, '2026-06-15 21:55:47.517387+00', '2026-07-22 20:26:46.954874+00', 48, 10, 80, 150, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('buffalo-bliss', 'Buffalo Bliss', 'Buffalo chicken, blue cheese crumbles, mozzarella, ranch dressing, red onions', 80.00, 'pizza', 'https://framerusercontent.com/images/fOcW4cqVIKe7O6jovEeqZ46Cg.png', 'Dairy, Gluten, Eggs', 'Calories: 310 · Fat: 15g · Carbs: 28g · Protein: 14g', 'from', false, 10, '2026-06-08 23:07:53.87796+00', '2026-07-22 18:54:28.142722+00', 25, 5, 80, 150, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('buffalo-wings', 'Buffalo Wings', 'Chicken wings, buffalo sauce, celery sticks, blue cheese dip', 89.90, 'sides', 'https://framerusercontent.com/images/5HkrLakvJ1QS8k9yeljgtboX9A.png', 'Dairy (blue cheese dip)', 'Calories: 430 · Fat: 31g · Carbs: 6g · Protein: 32g', '/6 wings', false, 0, '2026-06-08 23:07:53.87796+00', '2026-07-22 22:52:52.568223+00', 38, 5, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('caesar-salad', 'Classic Caesar Salad', 'Romaine, Parmesan, croutons, Caesar dressing', 64.90, 'sides', 'https://framerusercontent.com/images/8LagT2GMawnySp6zGEeZrsG4JJU.png', 'Dairy, Gluten, Eggs', 'Calories: 310 · Fat: 24g · Carbs: 17g · Protein: 8g', NULL, false, 10, '2026-06-08 23:07:53.87796+00', '2026-07-22 22:53:01.389739+00', 20, 5, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('cannoli', 'Classic Cannoli', 'Cannoli shells, ricotta, powdered sugar, chocolate chips, vanilla', 5.99, 'deserts', 'https://framerusercontent.com/images/Ru7hW8Qi1bQ8fHES0Gh6mmxA.png', 'Dairy, Gluten, Eggs', 'Calories: 350 · Fat: 18g · Carbs: 42g · Protein: 8g', '/2 cannoli', true, 20, '2026-06-15 21:55:47.517387+00', '2026-07-13 05:04:04.179233+00', 48, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('cape-town', 'Cape Town', 'Steak beef, chicken, mince, mushrooms, onions, green pepper & fresh tomatoes.', 105.00, 'pizza', 'https://raw.githubusercontent.com/BonganiCacambile/sweet-lovely-634f24d4/main/Cape_Town-removebg-preview.png', NULL, NULL, NULL, true, 0, '2026-07-15 15:38:15.7915+00', '2026-07-23 13:46:56.763913+00', 19, 5, 105, 195, '{"Steak beef",chicken,mince,mushrooms,onions,"green pepper & fresh tomatoes."}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('caramel-frappe', 'Caramel Frappé', 'Coffee, milk, caramel syrup, whipped cream, ice', 5.99, 'drinks', 'https://framerusercontent.com/images/e6wGiwadjdC8f3V7LauaQ6HyT8.png', 'Dairy', 'Calories: 280 · Fat: 11g · Carbs: 41g · Protein: 5g', NULL, true, 130, '2026-06-15 21:55:47.517387+00', '2026-06-15 21:55:47.517387+00', 50, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('cheese-avalanche', 'Margarita', 'Mozzarella, cheddar, Parmesan, gouda, ricotta, marinara sauce, oregano', 80.00, 'pizza', 'https://framerusercontent.com/images/Q4djsExkm2dVJLND8pnRkbmHKy8.png', 'Dairy, Gluten', 'Calories: 340 · Fat: 18g · Carbs: 29g · Protein: 16g', 'from', true, 0, '2026-06-08 23:07:53.87796+00', '2026-07-14 19:46:11.140491+00', 12, 5, 80, 155, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('chicken-mayo', 'Chicken Mayo', 'Chicken with Mayonnaise, onions, green pepper and cheese.', 80.00, 'pizza', 'https://raw.githubusercontent.com/BonganiCacambile/sweet-lovely-634f24d4/main/Chicken_Mayo-removebg-preview.png', NULL, NULL, NULL, true, 0, '2026-07-15 15:48:57.995037+00', '2026-07-23 13:46:56.763913+00', 20, 5, 80, 155, '{"Chicken with Mayonnaise",onions,"green pepper and cheese."}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('chocolate-shake', 'Chocolate Milkshake', 'Chocolate ice cream, milk, chocolate syrup, whipped cream', 6.50, 'drinks', 'https://framerusercontent.com/images/EkkZLIaKFdPxUlbZmBpnvY65CA.png', 'Dairy', 'Calories: 350 · Fat: 15g · Carbs: 48g · Protein: 8g', NULL, true, 110, '2026-06-15 21:55:47.517387+00', '2026-06-15 21:55:47.517387+00', 50, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('coconut-water', 'Coconut Water Cooler', 'Fresh coconut water, lime juice, mint, ice', 3.99, 'drinks', 'https://framerusercontent.com/images/T2Y59fsEAALVITHlwJ6Q6qIfXM.png', 'None', 'Calories: 60 · Carbs: 15g', NULL, true, 40, '2026-06-15 21:55:47.517387+00', '2026-06-18 03:06:42.302773+00', 49, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('cola', 'Classic Cola', 'Carbonated water, syrup, caramel color, caffeine', 2.50, 'drinks', 'https://framerusercontent.com/images/EPNDN5Z7pJqFluBKR5CiYN6BCk.png', 'None', 'Calories: 140 · Carbs: 39g', NULL, true, 10, '2026-06-15 21:55:47.517387+00', '2026-07-13 05:04:04.179233+00', 48, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('cold-brew', 'Cold Brew Coffee', 'Cold-brewed coffee, ice', 3.99, 'drinks', 'https://framerusercontent.com/images/tIfpe9e1OErjHRIbmmQBkDwQM1s.png', 'None', 'Calories: 5', NULL, true, 100, '2026-06-15 21:55:47.517387+00', '2026-06-15 21:55:47.517387+00', 50, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('firecracker-inferno', 'Mexican', 'Spicy pepperoni, jalapeños, crushed red pepper, mozzarella, marinara, sriracha drizzle', 80.00, 'pizza', 'https://framerusercontent.com/images/lp6wNgrYu7ClOrMG4ibaVQNDWLo.png', 'Dairy, Gluten', 'Calories: 280 · Fat: 14g · Carbs: 28g · Protein: 12g', 'from', false, 110, '2026-06-15 21:55:47.517387+00', '2026-07-22 18:55:58.933165+00', 47, 10, 80, 150, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('garden-delight', 'Garden Delight', 'Zucchini, bell peppers, cherry tomatoes, spinach, red onions, mozzarella, pesto sauce', 80.00, 'pizza', 'https://framerusercontent.com/images/Jo0m3edxzWNVUCgzB4ukskOgTHw.png', 'Dairy, Gluten, Nuts', 'Calories: 240 · Fat: 11g · Carbs: 27g · Protein: 10g', 'from', false, 50, '2026-06-15 21:55:47.517387+00', '2026-07-22 18:55:04.448028+00', 46, 10, 80, 150, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('garlic-breadsticks', 'Garlic Parmesan Breadsticks', 'Freshly baked breadsticks, garlic butter, Parmesan, parsley', 5.99, 'sides', 'https://framerusercontent.com/images/9j2NHhkAXP2iAtcjjDAsukDeTQY.png', 'Dairy, Gluten', 'Calories: 350 · Fat: 16g · Carbs: 42g · Protein: 9g', '/6 pieces', false, 50, '2026-06-15 21:55:47.517387+00', '2026-07-22 22:53:44.344687+00', 50, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('garlic-supreme', 'Garlic Supreme', 'Roasted garlic, caramelized onions, mozzarella, Parmesan, Alfredo, fresh parsley', 80.00, 'pizza', 'https://framerusercontent.com/images/Q2rEr3IGpX893CKsEuhm5IGMKk.png', 'Dairy, Gluten', 'Calories: 270 · Fat: 13g · Carbs: 27g · Protein: 11g', 'from', false, 90, '2026-06-15 21:55:47.517387+00', '2026-07-22 20:27:08.627146+00', 50, 10, 80, 150, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('greek', 'Greek', 'Mince, Onion, Ham and Cheese.', 80.00, 'pizza', 'https://raw.githubusercontent.com/BonganiCacambile/sweet-lovely-634f24d4/main/Greek.png', NULL, NULL, NULL, true, 0, '2026-07-22 18:25:19.944717+00', '2026-07-24 05:46:05.978297+00', 20, 5, 80, 155, '{Mince,Onion,"Ham and Cheese."}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('green-lemonade', 'Green Tea Lemonade', 'Brewed green tea, lemon juice, sugar, ice', 3.99, 'drinks', 'https://framerusercontent.com/images/npNVZEAs2uN3JKihJpXH4G5SLs.png', 'None', 'Calories: 100 · Carbs: 25g', NULL, true, 60, '2026-06-15 21:55:47.517387+00', '2026-06-15 21:55:47.517387+00', 50, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('gypsy', 'Gypsy', 'chicken with sauce, onions, green pepper, mushrooms and cheese.', 80.00, 'pizza', 'https://raw.githubusercontent.com/BonganiCacambile/sweet-lovely-634f24d4/main/Gypsy-removebg-preview.png', NULL, NULL, NULL, true, 0, '2026-07-22 18:27:06.519747+00', '2026-07-23 13:46:56.763913+00', 20, 5, 80, 155, '{"chicken with sauce",onions,"green pepper","mushrooms and cheese."}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('hawaiian', 'HAWAIIAN', 'Ham, pineapple and cheese.', 80.00, 'pizza', 'https://raw.githubusercontent.com/BonganiCacambile/sweet-lovely-634f24d4/main/Hawain-removebg-preview.png', NULL, NULL, NULL, true, 0, '2026-07-22 18:36:47.889418+00', '2026-07-23 13:46:56.763913+00', 20, 5, 80, 155, '{Ham,"pineapple and cheese."}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('hawaiian-heatwave', 'Hawaiian Heatwave', 'Grilled pineapple, Canadian bacon, mozzarella, marinara sauce, jalapeños', 80.00, 'pizza', 'https://framerusercontent.com/images/z0tpcmuGY42myUTNyLF9LCXg.png', 'Dairy, Gluten', 'Calories: 270 · Fat: 11g · Carbs: 30g · Protein: 12g', 'from', false, 30, '2026-06-15 21:55:47.517387+00', '2026-07-22 18:54:55.713709+00', 41, 10, 80, 150, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('hot-chocolate', 'Hot Chocolate', 'Milk, cocoa powder, sugar, whipped cream', 3.99, 'drinks', 'https://framerusercontent.com/images/olKbdfRkDrsCIjYs4ZNyoDyZh8g.png', 'Dairy', 'Calories: 250 · Fat: 11g · Carbs: 32g · Protein: 8g', NULL, true, 140, '2026-06-15 21:55:47.517387+00', '2026-06-15 21:55:47.517387+00', 50, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('ilitha-park', 'Ilitha Park', 'Ham, pineapple, mushrooms, onions, green pepper and cheese.', 80.00, 'pizza', 'https://raw.githubusercontent.com/BonganiCacambile/sweet-lovely-634f24d4/main/Ilitha%20Park.png', NULL, NULL, NULL, true, 0, '2026-07-22 18:40:46.657392+00', '2026-07-23 13:46:56.763913+00', 20, 5, 80, 155, '{Ham,pineapple,mushrooms,onions,"green pepper and cheese."}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('jalapeno-poppers', 'Zesty Jalapeño Poppers', 'Breaded jalapeños stuffed with cream cheese, ranch dressing', 6.99, 'sides', 'https://framerusercontent.com/images/v22l8NZfmOTbAFs0d5EbWfiMAg.png', 'Dairy, Gluten, Eggs', 'Calories: 380 · Fat: 22g · Carbs: 35g · Protein: 8g', '/6 pieces', false, 30, '2026-06-15 21:55:47.517387+00', '2026-07-22 22:53:23.438511+00', 49, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('khayelitsha', 'Khayelitsha', 'Steak beef, mushrooms, onions, green pepper, cheese and fresh tomatoes.', 85.00, 'pizza', 'https://raw.githubusercontent.com/BonganiCacambile/sweet-lovely-634f24d4/main/Khayelitsha-removebg-preview.png', NULL, NULL, NULL, true, 0, '2026-07-15 15:42:47.119155+00', '2026-07-23 13:46:56.763913+00', 20, 5, 85, 165, '{"Steak beef",mushrooms,onions,"green pepper","cheese and fresh tomatoes."}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('lava-cake', 'Chocolate Lava Cake', 'Dark chocolate, butter, eggs, sugar, flour, vanilla, powdered sugar', 6.99, 'deserts', 'https://framerusercontent.com/images/oBhv3dWqSzhJiOXKFp8TTQYurWE.png', 'Dairy, Gluten, Eggs', 'Calories: 450 · Fat: 28g · Carbs: 44g · Protein: 6g', NULL, true, 50, '2026-06-15 21:55:47.517387+00', '2026-06-15 21:55:47.517387+00', 50, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('lemon-tea', 'Lemon Iced Tea', 'Brewed black tea, lemon juice, sugar, ice', 3.50, 'drinks', 'https://framerusercontent.com/images/GrMb28ZBimSdmMOxXPl9kD2dlE.png', 'None', 'Calories: 120 · Car query params, '); 
    "password": ""; 
    
    var(--tw-gradient-from-position); 
    // 1.5x line-height;
    const [data, setData] = useState();
    {"content":""}
    ;  /* comment */
    INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('lemon-tea', 'Lemon Iced Tea', 'Brewed black tea, lemon juice, sugar, ice', 3.50, 'drinks', 'https://framerusercontent.com/images/GrMb28ZBimSdmMOxXPl9kD2dlE.png', 'None', 'Calories: 120 · Carbs: 30g', NULL, true, 20, '2026-06-15 21:55:47.517387+00', '2026-07-12 19:39:05.908503+00', 49, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('limeade', 'Limeade Spritzer', 'Lime juice, sparkling water, sugar, ice', 3.99, 'drinks', 'https://framerusercontent.com/images/yGzPQ8ney2W9hfUPI3xLyZvCujI.png', 'None', 'Calories: 110 · Carbs: 29g', NULL, true, 50, '2026-06-15 21:55:47.517387+00', '2026-06-15 21:55:47.517387+00', 50, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('mango-smoothie', 'Mango Smoothie', 'Fresh mango, yogurt, ice, honey', 4.99, 'drinks', 'https://framerusercontent.com/images/M1MzsJOs5zYPAhZxzEc3a4ANDrw.png', 'Dairy', 'Calories: 220 · Fat: 3g · Carbs: 48g · Protein: 5g', NULL, true, 90, '2026-06-15 21:55:47.517387+00', '2026-06-15 21:55:47.517387+00', 50, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('margarita-muse', 'Margarita Muse', 'Fresh mozzarella, ripe tomatoes, basil, EVOO, sea salt, marinara sauce', 80.00, 'pizza', 'https://framerusercontent.com/images/O35ad4eRtufs0gpp6JZXayT5IM.png', 'Dairy, Gluten', 'Calories: 220 · Fat: 10g · Carbs: 26g · Protein: 9g', 'from', false, 100, '2026-06-08 23:07:53.87796+00', '2026-07-22 20:27:36.845018+00', 37, 5, 80, 150, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('matcha-latte', 'Matcha Latte', 'Matcha green tea powder, milk, honey, ice', 5.99, 'drinks', 'https://framerusercontent.com/images/RU0prChVZMldKW9jnFH9P8QuXjc.png', 'Dairy', 'Calories: 170 · Fat: 6g · Carbs: 24g · Protein: 6g', NULL, true, 120, '2026-06-15 21:55:47.517387+00', '2026-06-15 21:55:47.517387+00', 50, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('mexican-hot', 'Mexican Hot', 'Mince, Onion, green pepper chillies and cheese.', 80.00, 'pizza', 'https://raw.githubusercontent.com/BonganiCacambile/sweet-lovely-634f24d4/main/Mexican-removebg-preview%20(1).png', NULL, NULL, NULL, true, 0, '2026-07-22 18:42:48.399998+00', '2026-07-23 13:46:56.763913+00', 20, 5, 80, 155, '{Mince,Onion,"green pepper chillies and cheese."}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('mozzarella-sticks', 'Mozzarella Sticks', 'Breaded mozzarella sticks, marinara sauce', 79.90, 'sides', 'https://framerusercontent.com/images/B0jk06Tv3FYjGVJFSdifH3Zt2w.png', 'Dairy, Gluten, Eggs', 'Calories: 450 · Fat: 25g · Carbs: 39g · Protein: 18g', '/6 sticks', false, 40, '2026-06-08 23:07:53.87796+00', '2026-07-22 22:53:35.672496+00', 20, 5, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('nutella-pizza', 'Nutella Pizza', 'Pizza dough, Nutella, powdered sugar, strawberries, whipped cream', 7.99, 'deserts', 'https://framerusercontent.com/images/pRzalLce4KvcQSggYuXBvUC174.png', 'Dairy, Gluten', 'Calories: 480 · Fat:  slty9.6x soit slty 90vw 60px 1rem 1em 1.5rem 2rem 4rem 8rem 16rem 32rem 64rem 100% 100vh 100vw 50% 33% 25% 20% 75% 66% auto none inherit initial unset 100% 100vh 100vw 50% 33% 25% 20% 75% 66% auto none inherit initial unset 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100', NULL, true, 0, '2026-06-15 21:55:47.517387+00', '2026-06-18 00:10:46.313576+00', 49, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('nutella-pizza', 'Nutella Pizza', 'Pizza dough, Nutella, powdered sugar, strawberries, whipped cream', 7.99, 'deserts', 'https://framerusercontent.com/images/pRzalLce4KvcQSggYuXBvUC174.png', 'Dairy, Gluten', 'Calories: 480 · Fat: 22g · Carbs: 62g · Protein: 7g', NULL, true, 0, '2026-06-15 21:55:47.517387+00', '2026-06-18 00:10:46.313576+00', 49, 10, NULL, NULL, '{}', NULL, NULL, NULL, NULL, false);
INSERT INTO public."products" ("slug", "title", "description", "price_zar", "category_slug", "image", "allergens", "nutrition", "portion", "is_active", "sort_order", "created_at", "updated_at", "stock", "low_stock_threshold", "price_medium_zar", "price_large_zar", "ingredients", "calories", "fat_g", "carbs_g", "protein_g", "size_selection_enabled") VALUES ('orange-juice', 'Orange Juice', 'Freshly squeezed oranges', 3.99, 'drinks', 'https://framerusercontent.com/images/9Cicx54hrMJ97UB6dKmDk7nkA.png', 'None', 'Calories: 160 · Carbs: 38g · Protein: 2g', NULL, true, 70, '2026-06-15 21abase_user: sweet_n_lovely_app: 'super_admin'
    role: 'super_admin';
    
    -- this is a comment
    -- this is another comment
    /* multi
    line comment */
    SELECT * FROM users;
    CREATE TABLE users (id UUID PRIMARY KEY);
    DROP TABLE users;
    INSERT INTO users VALUES ('1');
    UPDATE users SET name = 'test' WHERE id = '1';
    DELETE FROM users WHERE id = '1';
    ALTER TABLE users ADD COLUMN name TEXT;
    CREATE INDEX idx_users ON users(name);
    CREATE OR REPLACE FUNCTION test() RETURNS VOID AS $$ BEGIN END; $$ LANGUAGE plpgsql;
    GRANT SELECT ON users TO public;
    REVOKE SELECT ON users FROM public;
    SET search_path TO public;
    
    # Project Memory
    # Core
    # ...