-- Step 5: Realtime publication + replica identity
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN CREATE PUBLICATION supabase_realtime; END IF; END $$;

ALTER TABLE public.categories REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.categories; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.products REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.products; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.orders REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.orders; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.order_items REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.order_items; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.reviews REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.reviews; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.notifications REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.audit_logs REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.audit_logs; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.inventory_movements REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.inventory_movements; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.content_pages REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.content_pages; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.integrations REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.integrations; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.system_settings REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.system_settings; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.promotions REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.promotions; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.discounts REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.discounts; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.reservations REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.reservations; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.loyalty_programs REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.loyalty_programs; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.loyalty_accounts REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.loyalty_accounts; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.banners REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.banners; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.store_hours REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.store_hours; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.featured_items REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.featured_items; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.user_addresses REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.user_addresses; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.home_popular_items REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.home_popular_items; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.home_hot_deals REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.home_hot_deals; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.home_specials REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.home_specials; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.home_banners REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.home_banners; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.home_section_visibility REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.home_section_visibility; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.admin_presence REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.admin_presence; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.home_desserts REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.home_desserts; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.pizza_toppings REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.pizza_toppings; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE public.product_sizes REPLICA IDENTITY FULL;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.product_sizes; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
