// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5352a114c0b2f653 "Pepper (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * city?: string // City
 * address?: string // Address
 * mailLink?: string // Mail Link
 * phoneLink?: string // Phone Link
 * email?: string // Email
 * telephone?: string // Telephone
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-U7XD74U4.js";
import { className, css, fonts } from "./chunks/chunk-BW6CAMPU.js";
import { routes } from "./chunks/chunk-H6F5WHVF.js";

// virtual:address-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/h1CjDUnyECSKCRG24koh/PY6SzViVEbOGRNcJ8Sqj/cAvx8kLre.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/S9LLofDMwrCi84AT3GjF/AIolnStE28jPSqRApWBE/JSZpJHaKB.js
import { fontStore } from "unframer";
fontStore.loadFonts([]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css3 = [
	".framer-U7wfP .framer-styles-preset-pf0s9w:not(.rich-text-wrapper), .framer-U7wfP .framer-styles-preset-pf0s9w.rich-text-wrapper a { --framer-link-current-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #1a1a1a); --framer-link-current-text-decoration: underline; --framer-link-hover-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #1a1a1a); --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, #808080); --framer-link-text-decoration: none; }",
];
var className3 = "framer-U7wfP";

// /:https://framerusercontent.com/modules/h1CjDUnyECSKCRG24koh/PY6SzViVEbOGRNcJ8Sqj/cAvx8kLre.js
var serializationHash = "framer-WquCg";
var variantClassNames = {
	eH6Gevr3z: "framer-v-y9w1tc",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	address,
	city,
	email,
	height,
	id,
	mailLink,
	phoneLink,
	telephone,
	width,
	...props
}) => {
	return {
		...props,
		bXus_xZwX: address ?? props.bXus_xZwX ?? "113 E31st St, New York, NY 10016",
		DMM8KEXij: telephone ?? props.DMM8KEXij ?? "+01 222 555 444",
		fzDNa8OkM: phoneLink ?? props.fzDNa8OkM,
		VlXdzvRti: email ?? props.VlXdzvRti ?? "newyork@pepper.pizza",
		Y15ZtGory: mailLink ?? props.Y15ZtGory,
		z0ivRLtzW: city ?? props.z0ivRLtzW ?? "New York:",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		z0ivRLtzW: z0ivRLtzW2,
		bXus_xZwX: bXus_xZwX2,
		Y15ZtGory: Y15ZtGory2,
		fzDNa8OkM: fzDNa8OkM2,
		VlXdzvRti: VlXdzvRti2,
		DMM8KEXij: DMM8KEXij2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "eH6Gevr3z",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-y9w1tc",
							className4,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"eH6Gevr3z"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-13zxv75"}
							fonts={["Inter", "Inter-Bold"]}
							layoutDependency={layoutDependency}
							layoutId={"JoURbvFf2"}
							text={z0ivRLtzW2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-146xxk6"}
									data-styles-preset={"OIpMKy3L7"}
									dir={"auto"}
									style={{
										"--framer-text-alignment": "left",
									}}
								>
									<motion.strong>{"New York:"}</motion.strong>
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-hc4hsc"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"q1JdGLXrC"}
							text={bXus_xZwX2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-146xxk6"}
									data-styles-preset={"OIpMKy3L7"}
									dir={"auto"}
									style={{
										"--framer-text-alignment": "left",
									}}
								>
									{"113 E31st St, New York, NY 10016"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-uy6z0u"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"N9aL1BJC7"}
							text={VlXdzvRti2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-ctw6nh"}
									data-styles-preset={"qnHYitKoE"}
									dir={"auto"}
								>
									<Link
										href={Y15ZtGory2}
										motionChild={true}
										nodeId={"N9aL1BJC7"}
										openInNewTab={true}
										relValues={[]}
										scopeId={"cAvx8kLre"}
										smoothScroll={false}
									>
										<motion.a
											className={"framer-styles-preset-pf0s9w"}
											data-styles-preset={"JSZpJHaKB"}
										>
											{"newyork@pepper.pizza"}
										</motion.a>
									</Link>
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1cfb2w0"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"m9BLrGiCi"}
							text={DMM8KEXij2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-ctw6nh"}
									data-styles-preset={"qnHYitKoE"}
									dir={"auto"}
								>
									<Link
										href={fzDNa8OkM2}
										motionChild={true}
										nodeId={"m9BLrGiCi"}
										openInNewTab={true}
										relValues={[]}
										scopeId={"cAvx8kLre"}
										smoothScroll={false}
									>
										<motion.a
											className={"framer-styles-preset-pf0s9w"}
											data-styles-preset={"JSZpJHaKB"}
										>
											{"+01 222 555 444"}
										</motion.a>
									</Link>
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WquCg.framer-1lchvzv, .framer-WquCg .framer-1lchvzv { display: block; }",
	".framer-WquCg.framer-y9w1tc { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 264px; }",
	".framer-WquCg .framer-13zxv75, .framer-WquCg .framer-hc4hsc, .framer-WquCg .framer-uy6z0u, .framer-WquCg .framer-1cfb2w0 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css,
	...css2,
	...css3,
];
var FramercAvx8kLre = withCSS(Component, css4, "framer-WquCg");
var stdin_default = FramercAvx8kLre;
FramercAvx8kLre.displayName = "Address Card";
FramercAvx8kLre.defaultProps = {
	height: 112,
	width: 264,
};
addPropertyControls(FramercAvx8kLre, {
	z0ivRLtzW: {
		defaultValue: "New York:",
		displayTextArea: false,
		title: "City",
		type: ControlType.String,
	},
	bXus_xZwX: {
		defaultValue: "113 E31st St, New York, NY 10016",
		displayTextArea: false,
		title: "Address",
		type: ControlType.String,
	},
	Y15ZtGory: {
		title: "Mail Link",
		type: ControlType.Link,
	},
	fzDNa8OkM: {
		title: "Phone Link",
		type: ControlType.Link,
	},
	VlXdzvRti: {
		defaultValue: "newyork@pepper.pizza",
		displayTextArea: false,
		title: "Email",
		type: ControlType.String,
	},
	DMM8KEXij: {
		defaultValue: "+01 222 555 444",
		displayTextArea: false,
		title: "Telephone",
		type: ControlType.String,
	},
});
addFonts(
	FramercAvx8kLre,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:address-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5352a114c0b2f6533408ce29eda21dd74155cc4d0edaebe1b159ba55a597a9fd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AddressCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5352a114c0b2f6533408ce29eda21dd74155cc4d0edaebe1b159ba55a597a9fd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var address_card_default = ComponentWithRoot;
export { address_card_default as default };
