// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a377177818209678 "Pepper (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default - Small' | 'Secondary - Small - New Tab' | 'Blank - Small - New Tab' | 'Secondary - Big' | 'Default - Big' | 'Default - Small - New Tab' // Variant
 * title?: string // Title
 * link?: string // Link
}} Props

 */
import { routes } from "./chunks/chunk-H6F5WHVF.js";

// virtual:button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/m9ift3X4UVpgKwfEyUON/qHGuJIF0SEllFqbyPv03/j3mgIQlMk.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	C8LcdsPcq: {
		hover: true,
	},
	eJF7LtJ82: {
		hover: true,
	},
	M5tCFnvqR: {
		hover: true,
	},
	Te0yMoM0l: {
		hover: true,
	},
	yg4OUlUbG: {
		hover: true,
	},
	YUJ4R_SbY: {
		hover: true,
	},
};
var cycleOrder = [
	"eJF7LtJ82",
	"YUJ4R_SbY",
	"Te0yMoM0l",
	"yg4OUlUbG",
	"M5tCFnvqR",
	"C8LcdsPcq",
];
var serializationHash = "framer-sTWG3";
var variantClassNames = {
	C8LcdsPcq: "framer-v-ura6f9",
	eJF7LtJ82: "framer-v-wxj71d",
	M5tCFnvqR: "framer-v-cebnyb",
	Te0yMoM0l: "framer-v-xryac7",
	yg4OUlUbG: "framer-v-1qm2mdm",
	YUJ4R_SbY: "framer-v-1fcbvei",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transition2 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1.02,
	skewX: 0,
	skewY: 0,
	transition: transition2,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Blank - Small - New Tab": "Te0yMoM0l",
	"Default - Big": "M5tCFnvqR",
	"Default - Small - New Tab": "C8LcdsPcq",
	"Default - Small": "eJF7LtJ82",
	"Secondary - Big": "yg4OUlUbG",
	"Secondary - Small - New Tab": "YUJ4R_SbY",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, link, title, width, ...props }) => {
	return {
		...props,
		lJNtxFrg5: link ?? props.lJNtxFrg5,
		O5tlPGRu3: title ?? props.O5tlPGRu3 ?? "Button",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "eJF7LtJ82",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		O5tlPGRu3: O5tlPGRu32,
		lJNtxFrg5: lJNtxFrg52,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "eJF7LtJ82",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={lJNtxFrg52}
						motionChild={true}
						nodeId={"eJF7LtJ82"}
						scopeId={"j3mgIQlMk"}
						{...addPropertyOverrides(
							{
								C8LcdsPcq: {
									openInNewTab: true,
								},
								Te0yMoM0l: {
									openInNewTab: true,
								},
								yg4OUlUbG: {
									openInNewTab: false,
								},
								YUJ4R_SbY: {
									openInNewTab: true,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-wxj71d", className, classNames)} framer-vm0kzc`}
							data-framer-name={"Default - Small"}
							layoutDependency={layoutDependency}
							layoutId={"eJF7LtJ82"}
							ref={refBinding}
							style={{
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
								boxShadow: "0px 0px 10px 0px rgba(255, 0, 60, 0)",
								...style,
							}}
							variants={{
								"C8LcdsPcq-hover": {
									boxShadow: "0px 8px 20px 0px rgba(255, 0, 60, 0.2)",
								},
								"eJF7LtJ82-hover": {
									boxShadow: "0px 8px 20px 0px rgba(255, 0, 60, 0.2)",
								},
								"M5tCFnvqR-hover": {
									boxShadow: "0px 8px 20px 0px rgba(255, 0, 60, 0.2)",
								},
								"Te0yMoM0l-hover": {
									boxShadow: "0px 0px 10px 0px rgba(255, 255, 255, 0.2)",
								},
								"yg4OUlUbG-hover": {
									boxShadow: "0px 8px 20px 0px rgba(255, 0, 60, 0.2)",
								},
								"YUJ4R_SbY-hover": {
									boxShadow: "0px 8px 20px 0px rgba(255, 0, 60, 0.2)",
								},
							}}
							{...addPropertyOverrides(
								{
									"C8LcdsPcq-hover": {
										"data-framer-name": void 0,
									},
									"eJF7LtJ82-hover": {
										"data-framer-name": void 0,
									},
									"M5tCFnvqR-hover": {
										"data-framer-name": void 0,
									},
									"Te0yMoM0l-hover": {
										"data-framer-name": void 0,
									},
									"yg4OUlUbG-hover": {
										"data-framer-name": void 0,
									},
									"YUJ4R_SbY-hover": {
										"data-framer-name": void 0,
									},
									C8LcdsPcq: {
										"data-framer-name": "Default - Small - New Tab",
									},
									M5tCFnvqR: {
										"data-framer-name": "Default - Big",
									},
									Te0yMoM0l: {
										"data-framer-name": "Blank - Small - New Tab",
									},
									yg4OUlUbG: {
										"data-framer-name": "Secondary - Big",
									},
									YUJ4R_SbY: {
										"data-framer-name": "Secondary - Small - New Tab",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1fkxf78"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"fnuzGEEOh"}
								style={{
									backgroundColor:
										"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51))",
									borderBottomLeftRadius: 48,
									borderBottomRightRadius: 48,
									borderTopLeftRadius: 48,
									borderTopRightRadius: 48,
								}}
								variants={{
									"C8LcdsPcq-hover": {
										backgroundColor:
											"var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 0, 60))",
									},
									"eJF7LtJ82-hover": {
										backgroundColor:
											"var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 153, 0))",
									},
									"M5tCFnvqR-hover": {
										backgroundColor:
											"var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 0, 60))",
									},
									Te0yMoM0l: {
										backgroundColor:
											"var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255))",
									},
									yg4OUlUbG: {
										backgroundColor:
											"var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 0, 60))",
									},
									YUJ4R_SbY: {
										backgroundColor:
											"var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 0, 60))",
									},
								}}
								whileHover={animation}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1qrv10"}
									fonts={["Inter-Medium"]}
									layoutDependency={layoutDependency}
									layoutId={"a_GZwGhMt"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={O5tlPGRu32}
									variants={{
										Te0yMoM0l: {
											"--extracted-r6o4lv":
												"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51))",
										},
									}}
									verticalAlignment={"center"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											M5tCFnvqR: {
												children: (
													<React.Fragment>
														<motion.p
															dir={"auto"}
															style={{
																"--font-selector": "SW50ZXItTWVkaXVt",
																"--framer-font-size": "20px",
																"--framer-font-weight": "500",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255)))",
															}}
														>
															{"Button"}
														</motion.p>
													</React.Fragment>
												),
											},
											Te0yMoM0l: {
												children: (
													<React.Fragment>
														<motion.p
															dir={"auto"}
															style={{
																"--font-selector": "SW50ZXItTWVkaXVt",
																"--framer-font-weight": "500",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51)))",
															}}
														>
															{"Button"}
														</motion.p>
													</React.Fragment>
												),
											},
											yg4OUlUbG: {
												children: (
													<React.Fragment>
														<motion.p
															dir={"auto"}
															style={{
																"--font-selector": "SW50ZXItTWVkaXVt",
																"--framer-font-size": "20px",
																"--framer-font-weight": "500",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255)))",
															}}
														>
															{"Button"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											dir={"auto"}
											style={{
												"--font-selector": "SW50ZXItTWVkaXVt",
												"--framer-font-weight": "500",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255)))",
											}}
										>
											{"Button"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-sTWG3.framer-vm0kzc, .framer-sTWG3 .framer-vm0kzc { display: block; }",
	".framer-sTWG3.framer-wxj71d { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-sTWG3 .framer-1fkxf78 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: 36px; justify-content: center; overflow: visible; padding: 0px 24px 0px 24px; position: relative; width: min-content; will-change: var(--framer-will-change-effect-override, transform); z-index: 1; }",
	".framer-sTWG3 .framer-1qrv10 { flex: none; height: 32px; position: relative; white-space: pre; width: auto; }",
	".framer-sTWG3.framer-v-1qm2mdm .framer-1fkxf78, .framer-sTWG3.framer-v-cebnyb .framer-1fkxf78 { height: 48px; padding: 0px 36px 0px 36px; }",
];
var Framerj3mgIQlMk = withCSS(Component, css, "framer-sTWG3");
var stdin_default = Framerj3mgIQlMk;
Framerj3mgIQlMk.displayName = "Button";
Framerj3mgIQlMk.defaultProps = {
	height: 36,
	width: 97,
};
addPropertyControls(Framerj3mgIQlMk, {
	variant: {
		options: [
			"eJF7LtJ82",
			"YUJ4R_SbY",
			"Te0yMoM0l",
			"yg4OUlUbG",
			"M5tCFnvqR",
			"C8LcdsPcq",
		],
		optionTitles: [
			"Default - Small",
			"Secondary - Small - New Tab",
			"Blank - Small - New Tab",
			"Secondary - Big",
			"Default - Big",
			"Default - Small - New Tab",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	O5tlPGRu3: {
		defaultValue: "Button",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	lJNtxFrg5: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	Framerj3mgIQlMk,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Te0yMoM0l",
	xl: "C8LcdsPcq",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a377177818209678b37adc5f263446ba17148664a97f412372f73ef06885d900"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a377177818209678b37adc5f263446ba17148664a97f412372f73ef06885d900"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_default = ComponentWithRoot;
export { button_default as default };
