// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5352a114c0b2f653 "Pepper (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * type?: string // Type
 * title?: string // Title
 * link?: string // Link
 * bubbleColor?: string // Bubble Color
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-YSF7EGQK.js";
import { Icon } from "./chunks/chunk-NI3BWCIH.js";
import { className, css, fonts } from "./chunks/chunk-BW6CAMPU.js";
import { routes } from "./chunks/chunk-H6F5WHVF.js";

// virtual:licensing-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/kjviAYvc33F6N1GvTKEG/DvDrYszNfNvx1fsP3khq/jxvyOiO39.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var enabledGestures = {
	QypixpTU0: {
		hover: true,
	},
};
var serializationHash = "framer-rxmZ4";
var variantClassNames = {
	QypixpTU0: "framer-v-8yio5",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	bubbleColor,
	height,
	id,
	link,
	title,
	type,
	width,
	...props
}) => {
	return {
		...props,
		cvlicU1Gm:
			bubbleColor ??
			props.cvlicU1Gm ??
			"var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 0, 60))",
		DDZEaSg_w: title ?? props.DDZEaSg_w ?? "PHOSPHOR",
		tf2XmSjX4: type ?? props.tf2XmSjX4 ?? "Icons",
		WclgvYc2M: link ?? props.WclgvYc2M,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		tf2XmSjX4: tf2XmSjX42,
		DDZEaSg_w: DDZEaSg_w2,
		WclgvYc2M: WclgvYc2M2,
		cvlicU1Gm: cvlicU1Gm2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "QypixpTU0",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={WclgvYc2M2}
						motionChild={true}
						nodeId={"QypixpTU0"}
						openInNewTab={true}
						scopeId={"jxvyOiO39"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-8yio5", className3, classNames)} framer-eghdgd`}
							data-border={true}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"QypixpTU0"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-31634a84-47e1-4076-8713-49e4511b2f24, rgb(230, 230, 230))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255))",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
								...style,
							}}
							{...addPropertyOverrides(
								{
									"QypixpTU0-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1ujw9ta"}
								data-framer-name={"Bubble"}
								layoutDependency={layoutDependency}
								layoutId={"H2VNbxyZj"}
								style={{
									backgroundColor: cvlicU1Gm2,
									borderBottomLeftRadius: 12,
									borderBottomRightRadius: 12,
									borderTopLeftRadius: 12,
									borderTopRightRadius: 12,
								}}
							/>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-s1gw7x"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"GJWxfMbaR"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={tf2XmSjX42}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-146xxk6"}
										data-styles-preset={"OIpMKy3L7"}
										dir={"auto"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128)))",
										}}
									>
										{"Icons"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-78i7oj"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"g6puP3W5L"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={DDZEaSg_w2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-8pfco1"}
										data-styles-preset={"xijQmTrDv"}
										dir={"auto"}
									>
										{"PHOSPHOR"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-1vigu1q"}
								data-framer-name={"Stack"}
								layoutDependency={layoutDependency}
								layoutId={"tgnQi8GvL"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-cuhwty"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"hnzW5T1lK"}
									style={{
										"--extracted-1eung3n":
											"var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									variants={{
										"QypixpTU0-hover": {
											"--extracted-1eung3n":
												"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(26, 26, 26))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"QypixpTU0-hover": {
												children: (
													<React.Fragment>
														<motion.h4
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1eung3n, var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(26, 26, 26)))",
															}}
														>
															{"Open Link"}
														</motion.h4>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h4
											dir={"auto"}
											style={{
												"--framer-text-color":
													"var(--extracted-1eung3n, var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128)))",
											}}
										>
											{"Open Link"}
										</motion.h4>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-75a1fo"}
									data-framer-name={"Icon"}
									layoutDependency={layoutDependency}
									layoutId={"rZq_F6f73"}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-vzgnst-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"ZeeIyCjM3-container"}
											nodeId={"ZeeIyCjM3"}
											rendersWithMotion={true}
											scopeId={"jxvyOiO39"}
											style={{
												rotate: 45,
											}}
											variants={{
												"QypixpTU0-hover": {
													rotate: 0,
												},
											}}
										>
											<Icon
												color={
													"var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128))"
												}
												height={"100%"}
												iconSearch={"House"}
												iconSelection={"ArrowUpRight"}
												id={"ZeeIyCjM3"}
												layoutId={"ZeeIyCjM3"}
												mirrored={false}
												selectByList={true}
												style={{
													height: "100%",
													width: "100%",
												}}
												weight={"light"}
												width={"100%"}
												{...addPropertyOverrides(
													{
														"QypixpTU0-hover": {
															color:
																"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(26, 26, 26))",
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-rxmZ4.framer-eghdgd, .framer-rxmZ4 .framer-eghdgd { display: block; }",
	".framer-rxmZ4.framer-8yio5 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; height: 240px; justify-content: space-between; overflow: hidden; padding: 24px; position: relative; text-decoration: none; width: 270px; will-change: var(--framer-will-change-override, transform); }",
	".framer-rxmZ4 .framer-1ujw9ta { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 9px); overflow: hidden; position: absolute; right: 24px; top: 24px; width: 9px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-rxmZ4 .framer-s1gw7x { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-rxmZ4 .framer-78i7oj { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-rxmZ4 .framer-1vigu1q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-rxmZ4 .framer-cuhwty { flex: 1 0 0px; height: auto; overflow: visible; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-rxmZ4 .framer-75a1fo { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 19px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 19px; }",
	".framer-rxmZ4 .framer-vzgnst-container { flex: none; height: 19px; left: calc(47.3684210526316% - 19px / 2); position: absolute; top: calc(47.3684210526316% - 19px / 2); width: 19px; z-index: 1; }",
	...css,
	...css2,
	'.framer-rxmZ4[data-border="true"]::after, .framer-rxmZ4 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerjxvyOiO39 = withCSS(Component, css3, "framer-rxmZ4");
var stdin_default = FramerjxvyOiO39;
FramerjxvyOiO39.displayName = "Licensing Card";
FramerjxvyOiO39.defaultProps = {
	height: 240,
	width: 270,
};
addPropertyControls(FramerjxvyOiO39, {
	tf2XmSjX4: {
		defaultValue: "Icons",
		displayTextArea: false,
		title: "Type",
		type: ControlType.String,
	},
	DDZEaSg_w: {
		defaultValue: "PHOSPHOR",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	WclgvYc2M: {
		title: "Link",
		type: ControlType.Link,
	},
	cvlicU1Gm: {
		defaultValue:
			'var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 0, 60)) /* {"name":"Fire Red/50"} */',
		title: "Bubble Color",
		type: ControlType.Color,
	},
});
addFonts(
	FramerjxvyOiO39,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:licensing-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5352a114c0b2f6533408ce29eda21dd74155cc4d0edaebe1b159ba55a597a9fd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LicensingCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5352a114c0b2f6533408ce29eda21dd74155cc4d0edaebe1b159ba55a597a9fd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var licensing_card_default = ComponentWithRoot;
export { licensing_card_default as default };
