// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a377177818209678 "Pepper (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Only Pizza - Desktop' | 'Only Pizza - Menu - Desktop' | 'Only Pizza - Tablet' | 'Others - Desktop' | 'Others - Tablet' | 'Others - Menu - Desktop' | 'Only Pizza - Menu - Mobile' | 'Others - Menu - Mobile' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * title?: string // Title
 * priceMedium?: string // Price - Medium
 * ingredients?: any // Ingredients
 * alergenWarnings?: string // Alergen Warnings
 * link?: string // Link
 * portion?: string // Portion
 * content?: any // Content
 * nutritionalInfo?: any // Nutritional Info
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-2XRBDIEF.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "../chunks/chunk-TEXBX6PP.js";
import { stdin_default } from "../chunks/chunk-RGEGD6RN.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "../chunks/chunk-YSF7EGQK.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-BW6CAMPU.js";
import { routes } from "../chunks/chunk-H6F5WHVF.js";

// virtual:menu-products/product-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/r01IYnJg50pCIoUpNtus/oJbUaRK5w9Q5VCS1gwRx/MxtevI0rb.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/agSMkOPtzVgNKJKYemII/6VyAs7vim7W1VyeTLYQv/aqu2QfUFH.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"Inter",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts5 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css5 = [
	'.framer-al4H8 .framer-styles-preset-zesw09:not(.rich-text-wrapper), .framer-al4H8 .framer-styles-preset-zesw09.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 12px; --framer-text-alignment: center; --framer-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #1a1a1a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className5 = "framer-al4H8";

// /:https://framerusercontent.com/modules/ZR5imqMuHA24Qp8bpMQV/QjhZ8y3hYjMfpMy3flox/GjNmQXS55.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([]);
var fonts6 = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css6 = [
	".framer-lj1KI .framer-styles-preset-uxjzqz:not(.rich-text-wrapper), .framer-lj1KI .framer-styles-preset-uxjzqz.rich-text-wrapper a { --framer-link-current-text-color: var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, #ffffff); --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, #ffffff); --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, #ffffff); --framer-link-text-decoration: none; }",
];
var className6 = "framer-lj1KI";

// /:https://framerusercontent.com/modules/N1XqS13Wy2LeCsY5QIKE/cqmWhDEPgxVpRlPPAgVy/irEsLKKYZ.js
import { fontStore as fontStore3 } from "unframer";
fontStore3.loadFonts([
	"Inter",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts7 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css7 = [
	'.framer-joqts .framer-styles-preset-1a2lisq:not(.rich-text-wrapper), .framer-joqts .framer-styles-preset-1a2lisq.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #1a1a1a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className7 = "framer-joqts";

// /:https://framerusercontent.com/modules/rALMZbZoWFsWj3aanI9j/8ndSEM2LGExw0Gvj3gkN/oSwZ59yDX.js
import { fontStore as fontStore4 } from "unframer";
fontStore4.loadFonts(["GF;Gabarito-800", "GF;Gabarito-900"]);
var fonts8 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Gabarito",
				source: "google",
				style: "normal",
				uiFamilyName: "Gabarito",
				url: "https://fonts.gstatic.com/s/gabarito/v9/QGYwz_0dZAGKJJ4t3FFkc3Q8AkNP9Pj2Y8W0EwItq6bFIg.woff2",
				weight: "800",
			},
			{
				cssFamilyName: "Gabarito",
				source: "google",
				style: "normal",
				uiFamilyName: "Gabarito",
				url: "https://fonts.gstatic.com/s/gabarito/v9/QGYwz_0dZAGKJJ4t3FFkc3Q8AkNP9Pj2SsW0EwItq6bFIg.woff2",
				weight: "900",
			},
		],
	},
];
var css8 = [
	'.framer-IXtgs .framer-styles-preset-a7kjrb:not(.rich-text-wrapper), .framer-IXtgs .framer-styles-preset-a7kjrb.rich-text-wrapper h2 { --framer-font-family: "Gabarito", sans-serif; --framer-font-family-bold: "Gabarito", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 50px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 800; --framer-font-weight-bold: 900; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 10px; --framer-text-alignment: start; --framer-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #333333); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-IXtgs .framer-styles-preset-a7kjrb:not(.rich-text-wrapper), .framer-IXtgs .framer-styles-preset-a7kjrb.rich-text-wrapper h2 { --framer-font-family: "Gabarito", sans-serif; --framer-font-family-bold: "Gabarito", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 44px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 800; --framer-font-weight-bold: 900; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 10px; --framer-text-alignment: start; --framer-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #333333); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-IXtgs .framer-styles-preset-a7kjrb:not(.rich-text-wrapper), .framer-IXtgs .framer-styles-preset-a7kjrb.rich-text-wrapper h2 { --framer-font-family: "Gabarito", sans-serif; --framer-font-family-bold: "Gabarito", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 800; --framer-font-weight-bold: 900; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 10px; --framer-text-alignment: start; --framer-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #333333); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className8 = "framer-IXtgs";

// /:https://framerusercontent.com/modules/cWEtutMvLEmthOjhINyx/kdZqVxpJ6dtMGJyLCyCU/R3hi4q1ar.js
import { fontStore as fontStore5 } from "unframer";
fontStore5.loadFonts([
	"Inter-Medium",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-MediumItalic",
]);
var fonts9 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/khkJkwSL66WFg8SX6Wa726c.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/0E7IMbDzcGABpBwwqNEt60wU0w.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/NTJ0nQgIF0gcDelS14zQ9NR9Q.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/QrcNhgEPfRl0LS8qz5Ln8olanl8.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JEXmejW8mXOYMtt0hyRg811kHac.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/Bo5CNzBv77CafbxOtKIkpw9egw.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/uy9s0iWuxiNnVt8EpTI3gzohpwo.woff2",
				weight: "500",
			},
		],
	},
];
var css9 = [
	'.framer-8PWtj .framer-styles-preset-lqlzfe:not(.rich-text-wrapper), .framer-8PWtj .framer-styles-preset-lqlzfe.rich-text-wrapper h5 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 12px; --framer-text-alignment: start; --framer-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #1a1a1a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-8PWtj .framer-styles-preset-lqlzfe:not(.rich-text-wrapper), .framer-8PWtj .framer-styles-preset-lqlzfe.rich-text-wrapper h5 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 12px; --framer-text-alignment: start; --framer-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #1a1a1a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-8PWtj .framer-styles-preset-lqlzfe:not(.rich-text-wrapper), .framer-8PWtj .framer-styles-preset-lqlzfe.rich-text-wrapper h5 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 12px; --framer-text-alignment: start; --framer-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #1a1a1a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className9 = "framer-8PWtj";

// /:https://framerusercontent.com/modules/1Qe3TGbo8KfpjnmgLOSW/mUmmSeiOJygHZwFTmXiu/sPnb8zgZ4.js
import { fontStore as fontStore6 } from "unframer";
fontStore6.loadFonts([
	"Inter-Medium",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-MediumItalic",
]);
var fonts10 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/khkJkwSL66WFg8SX6Wa726c.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/0E7IMbDzcGABpBwwqNEt60wU0w.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/NTJ0nQgIF0gcDelS14zQ9NR9Q.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/QrcNhgEPfRl0LS8qz5Ln8olanl8.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JEXmejW8mXOYMtt0hyRg811kHac.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ksvR4VsLksjpSwnC2fPgHRNMw.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/uy9s0iWuxiNnVt8EpTI3gzohpwo.woff2",
				weight: "500",
			},
		],
	},
];
var css10 = [
	'.framer-M2iL0 .framer-styles-preset-1yuvj0r:not(.rich-text-wrapper), .framer-M2iL0 .framer-styles-preset-1yuvj0r.rich-text-wrapper h6 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #333333; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-M2iL0 .framer-styles-preset-1yuvj0r:not(.rich-text-wrapper), .framer-M2iL0 .framer-styles-preset-1yuvj0r.rich-text-wrapper h6 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #333333; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-M2iL0 .framer-styles-preset-1yuvj0r:not(.rich-text-wrapper), .framer-M2iL0 .framer-styles-preset-1yuvj0r.rich-text-wrapper h6 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #333333; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className10 = "framer-M2iL0";

// /:https://framerusercontent.com/modules/wPk52x2FXUUJeql0WZTA/V3MKfyy9jon0rFeHEKhJ/vOxYm91Jf.js
import { fontStore as fontStore7 } from "unframer";
fontStore7.loadFonts(["GF;Gabarito-800", "GF;Gabarito-900"]);
var fonts11 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Gabarito",
				source: "google",
				style: "normal",
				uiFamilyName: "Gabarito",
				url: "https://fonts.gstatic.com/s/gabarito/v9/QGYwz_0dZAGKJJ4t3FFkc3Q8AkNP9Pj2Y8W0EwItq6bFIg.woff2",
				weight: "800",
			},
			{
				cssFamilyName: "Gabarito",
				source: "google",
				style: "normal",
				uiFamilyName: "Gabarito",
				url: "https://fonts.gstatic.com/s/gabarito/v9/QGYwz_0dZAGKJJ4t3FFkc3Q8AkNP9Pj2SsW0EwItq6bFIg.woff2",
				weight: "900",
			},
		],
	},
];
var css11 = [
	'.framer-NMcmo .framer-styles-preset-1kj8o89:not(.rich-text-wrapper), .framer-NMcmo .framer-styles-preset-1kj8o89.rich-text-wrapper h1 { --framer-font-family: "Gabarito", sans-serif; --framer-font-family-bold: "Gabarito", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 80px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 800; --framer-font-weight-bold: 900; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 12px; --framer-text-alignment: start; --framer-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #333333); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-NMcmo .framer-styles-preset-1kj8o89:not(.rich-text-wrapper), .framer-NMcmo .framer-styles-preset-1kj8o89.rich-text-wrapper h1 { --framer-font-family: "Gabarito", sans-serif; --framer-font-family-bold: "Gabarito", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 72px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 800; --framer-font-weight-bold: 900; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 12px; --framer-text-alignment: start; --framer-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #333333); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-NMcmo .framer-styles-preset-1kj8o89:not(.rich-text-wrapper), .framer-NMcmo .framer-styles-preset-1kj8o89.rich-text-wrapper h1 { --framer-font-family: "Gabarito", sans-serif; --framer-font-family-bold: "Gabarito", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 800; --framer-font-weight-bold: 900; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 12px; --framer-text-alignment: start; --framer-text-color: var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, #333333); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className11 = "framer-NMcmo";

// /:https://framerusercontent.com/modules/r01IYnJg50pCIoUpNtus/oJbUaRK5w9Q5VCS1gwRx/MxtevI0rb.js
var ButtonFonts = getFonts(stdin_default);
var enabledGestures = {
	TaTZpoRBy: {
		hover: true,
	},
};
var cycleOrder = [
	"DnzGOsfzr",
	"q4_8l_OzZ",
	"yBr80vEWy",
	"TaTZpoRBy",
	"myDAPps2s",
	"iEDHklQvm",
	"NkEZS5G9j",
	"ZiUjmlMWv",
];
var serializationHash = "framer-yeQSV";
var variantClassNames = {
	DnzGOsfzr: "framer-v-k9wk7",
	iEDHklQvm: "framer-v-1lurm80",
	myDAPps2s: "framer-v-srf1oa",
	NkEZS5G9j: "framer-v-jaeg78",
	q4_8l_OzZ: "framer-v-nvoup0",
	TaTZpoRBy: "framer-v-1pxosm6",
	yBr80vEWy: "framer-v-rydr9o",
	ZiUjmlMWv: "framer-v-p8wajo",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Only Pizza - Desktop": "DnzGOsfzr",
	"Only Pizza - Menu - Desktop": "q4_8l_OzZ",
	"Only Pizza - Menu - Mobile": "NkEZS5G9j",
	"Only Pizza - Tablet": "yBr80vEWy",
	"Others - Desktop": "TaTZpoRBy",
	"Others - Menu - Desktop": "iEDHklQvm",
	"Others - Menu - Mobile": "ZiUjmlMWv",
	"Others - Tablet": "myDAPps2s",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	alergenWarnings,
	content,
	height,
	id,
	image,
	ingredients,
	link,
	nutritionalInfo,
	portion,
	priceMedium,
	title,
	width,
	...props
}) => {
	return {
		...props,
		EKtkBiqHP: image ??
			props.EKtkBiqHP ?? {
				pixelHeight: 1024,
				pixelWidth: 1024,
				src: "https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?width=1024&height=1024",
				srcSet:
					"https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?width=1024&height=1024 1024w",
			},
		FZjwTwKXl: title ?? props.FZjwTwKXl ?? "Pepperoni Popper",
		GTORt8VJU: portion ?? props.GTORt8VJU ?? "/portion",
		gWA6po3g9: priceMedium ?? props.gWA6po3g9 ?? "$14.99",
		JoZ2UEEJT: nutritionalInfo ?? props.JoZ2UEEJT ?? (
			<React.Fragment>
				<motion.p>{"Dairy, Gluten"}</motion.p>
			</React.Fragment>
		),
		JV7xTZLzb: content ?? props.JV7xTZLzb ?? (
			<React.Fragment>
				<motion.p>{"Nutritional Info"}</motion.p>
			</React.Fragment>
		),
		mxkLNJQZN: alergenWarnings ?? props.mxkLNJQZN ?? "Dairy, Gluten",
		o9SibF6N9: link ?? props.o9SibF6N9,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "DnzGOsfzr",
		ZaUVK_Zrs: ingredients ?? props.ZaUVK_Zrs ?? (
			<React.Fragment>
				<motion.p>
					{
						"Double pepperoni, mozzarella, spicy marinara sauce, crushed red pepper, black olives"
					}
				</motion.p>
			</React.Fragment>
		),
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className12,
		layoutId,
		variant,
		EKtkBiqHP: EKtkBiqHP2,
		FZjwTwKXl: FZjwTwKXl2,
		gWA6po3g9: gWA6po3g92,
		ZaUVK_Zrs: ZaUVK_Zrs2,
		mxkLNJQZN: mxkLNJQZN2,
		o9SibF6N9: o9SibF6N92,
		GTORt8VJU: GTORt8VJU2,
		JV7xTZLzb: JV7xTZLzb2,
		JoZ2UEEJT: JoZ2UEEJT2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "DnzGOsfzr",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className3,
		className5,
		className11,
		className8,
		className4,
		className9,
		className10,
		className7,
		className6,
		className2,
		className,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (
			["q4_8l_OzZ", "iEDHklQvm", "NkEZS5G9j", "ZiUjmlMWv"].includes(baseVariant)
		)
			return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-k9wk7",
							className12,
							classNames,
						)}
						data-framer-name={"Only Pizza - Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"DnzGOsfzr"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color": "rgba(0, 0, 0, 0)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backgroundColor:
								"var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255))",
							borderBottomLeftRadius: 24,
							borderBottomRightRadius: 24,
							borderTopLeftRadius: 24,
							borderTopRightRadius: 24,
							...style,
						}}
						variants={{
							iEDHklQvm: {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-31634a84-47e1-4076-8713-49e4511b2f24, rgb(230, 230, 230))",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "dashed",
								"--border-top-width": "0px",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
							},
							myDAPps2s: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
								backgroundColor:
									"var(--token-5e6ca5e2-f7ae-4b0a-ac12-853f73b9de23, rgb(255, 245, 247))",
							},
							NkEZS5G9j: {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-31634a84-47e1-4076-8713-49e4511b2f24, rgb(230, 230, 230))",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "dashed",
								"--border-top-width": "0px",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
							},
							q4_8l_OzZ: {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-31634a84-47e1-4076-8713-49e4511b2f24, rgb(230, 230, 230))",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "dashed",
								"--border-top-width": "0px",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
							},
							TaTZpoRBy: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
								backgroundColor:
									"var(--token-5e6ca5e2-f7ae-4b0a-ac12-853f73b9de23, rgb(255, 245, 247))",
							},
							yBr80vEWy: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
							},
							ZiUjmlMWv: {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-31634a84-47e1-4076-8713-49e4511b2f24, rgb(230, 230, 230))",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "dashed",
								"--border-top-width": "0px",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
							},
						}}
						{...addPropertyOverrides(
							{
								"TaTZpoRBy-hover": {
									"data-framer-name": void 0,
								},
								iEDHklQvm: {
									"data-border": true,
									"data-framer-name": "Others - Menu - Desktop",
								},
								myDAPps2s: {
									"data-framer-name": "Others - Tablet",
								},
								NkEZS5G9j: {
									"data-border": true,
									"data-framer-name": "Only Pizza - Menu - Mobile",
								},
								q4_8l_OzZ: {
									"data-border": true,
									"data-framer-name": "Only Pizza - Menu - Desktop",
								},
								TaTZpoRBy: {
									"data-framer-name": "Others - Desktop",
								},
								yBr80vEWy: {
									"data-framer-name": "Only Pizza - Tablet",
								},
								ZiUjmlMWv: {
									"data-border": true,
									"data-framer-name": "Others - Menu - Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1t6erfq"}
							data-framer-name={"Photo"}
							layoutDependency={layoutDependency}
							layoutId={"zO1Q_34t3"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											24 +
											(((componentViewport?.height || 200) - 48 - 280) / 2 +
												0 +
												0) +
											-54,
									),
									sizes: "360px",
									...toResponsiveImage(EKtkBiqHP2),
								}}
								className={"framer-xuaifq"}
								data-framer-name={"Photo"}
								layoutDependency={layoutDependency}
								layoutId={"s2T63qIA3"}
								style={{
									borderBottomLeftRadius: 10,
									borderBottomRightRadius: 10,
									borderTopLeftRadius: 10,
									borderTopRightRadius: 10,
								}}
								transformTemplate={transformTemplate1}
								{...addPropertyOverrides(
									{
										iEDHklQvm: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 24 + 0,
												),
												sizes: "320px",
												...toResponsiveImage(EKtkBiqHP2),
											},
											transformTemplate: transformTemplate2,
										},
										myDAPps2s: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 24 + -20,
												),
												sizes: "280px",
												...toResponsiveImage(EKtkBiqHP2),
											},
											transformTemplate: transformTemplate2,
										},
										NkEZS5G9j: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														24 +
														(((componentViewport?.height || 200) - 72 - 290) /
															2 +
															0 +
															0) +
														-35,
												),
												sizes: "360px",
												...toResponsiveImage(EKtkBiqHP2),
											},
											transformTemplate: transformTemplate2,
										},
										q4_8l_OzZ: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 24 + 0,
												),
												sizes: "280px",
												...toResponsiveImage(EKtkBiqHP2),
											},
											transformTemplate: transformTemplate2,
										},
										yBr80vEWy: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 24 + -20,
												),
												sizes: "280px",
												...toResponsiveImage(EKtkBiqHP2),
											},
											transformTemplate: transformTemplate2,
										},
										ZiUjmlMWv: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														24 +
														(((componentViewport?.height || 200) - 72 - 290) /
															2 +
															0 +
															0) +
														-35,
												),
												sizes: "360px",
												...toResponsiveImage(EKtkBiqHP2),
											},
											transformTemplate: transformTemplate2,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
						<motion.div
							className={"framer-12pieyh"}
							layoutDependency={layoutDependency}
							layoutId={"mvYs4ytYO"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-13gjfch"}
								data-framer-name={"Title"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"icgDNiXNs"}
								text={FZjwTwKXl2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-1qlh3s0"}
										data-styles-preset={"v29eFMwtk"}
										dir={"auto"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										{"Pepperoni Popper"}
									</motion.h3>
								</React.Fragment>
							</RichText>
							{isDisplayed() && (
								<motion.div
									className={"framer-15jlfg5"}
									data-framer-name={"Alergens"}
									layoutDependency={layoutDependency}
									layoutId={"oYRcOmH2I"}
								>
									{isDisplayed() && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-e9osoi"}
											data-framer-name={"Alergen Warnings"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"Ka4v5IaUo"}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-zesw09"}
													data-styles-preset={"aqu2QfUFH"}
													dir={"auto"}
													style={{
														"--framer-text-alignment": "left",
													}}
												>
													{"Alergens:"}
												</motion.p>
											</React.Fragment>
										</RichText>
									)}
									{isDisplayed() && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-49w3mx"}
											data-framer-name={"Alergen Warnings"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"zvm3yzkr3"}
											text={mxkLNJQZN2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-zesw09"}
													data-styles-preset={"aqu2QfUFH"}
													dir={"auto"}
												>
													{"Dairy, Gluten"}
												</motion.p>
											</React.Fragment>
										</RichText>
									)}
								</motion.div>
							)}
							{isDisplayed() && (
								<motion.div
									className={"framer-l71ek3"}
									data-framer-name={"Nutritional Info"}
									layoutDependency={layoutDependency}
									layoutId={"Ubv84h4GA"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-6x38hl"}
										data-framer-name={"Ingredients"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"FTEGb9GXi"}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-zesw09"}
												data-styles-preset={"aqu2QfUFH"}
												dir={"auto"}
												style={{
													"--framer-text-alignment": "left",
												}}
											>
												{"Nutritional Info:"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-kii31b"}
										data-framer-name={"Alergen Warnings"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"CmejmmhkJ"}
										stylesPresetsClassNames={{
											a: "framer-styles-preset-uxjzqz",
											h1: "framer-styles-preset-1kj8o89",
											h2: "framer-styles-preset-a7kjrb",
											h3: "framer-styles-preset-1qlh3s0",
											h4: "framer-styles-preset-8pfco1",
											h5: "framer-styles-preset-lqlzfe",
											h6: "framer-styles-preset-1yuvj0r",
											p: "framer-styles-preset-1a2lisq",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												q4_8l_OzZ: {
													children: JoZ2UEEJT2,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										{JV7xTZLzb2}
									</RichText>
								</motion.div>
							)}
							<motion.div
								className={"framer-1mfy7nc"}
								data-framer-name={"Ingredients"}
								layoutDependency={layoutDependency}
								layoutId={"Hb7KaUgce"}
							>
								{isDisplayed() && (
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1vczlyq"}
										data-framer-name={"Ingredients"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"GGSk1ghUC"}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-zesw09"}
												data-styles-preset={"aqu2QfUFH"}
												dir={"auto"}
												style={{
													"--framer-text-alignment": "left",
												}}
											>
												{"Ingredients:"}
											</motion.p>
										</React.Fragment>
									</RichText>
								)}
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1mc3vpu"}
									data-framer-name={"Ingredients"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"JG01cGb7Z"}
									stylesPresetsClassNames={{
										a: "framer-styles-preset-uxjzqz",
										h1: "framer-styles-preset-1kj8o89",
										h2: "framer-styles-preset-a7kjrb",
										h3: "framer-styles-preset-1qlh3s0",
										h4: "framer-styles-preset-8pfco1",
										h5: "framer-styles-preset-lqlzfe",
										h6: "framer-styles-preset-1yuvj0r",
										p: "framer-styles-preset-1a2lisq",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									{ZaUVK_Zrs2}
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1f8ptlm"}
								data-framer-name={"Pricing"}
								layoutDependency={layoutDependency}
								layoutId={"e6nm2sQnP"}
							>
								<ComponentViewportProvider
									height={36}
									y={
										(componentViewport?.y || 0) +
										24 +
										(((componentViewport?.height || 200) - 48 - 280) / 2 +
											0 +
											0) +
										0 +
										159.2 +
										12
									}
									{...addPropertyOverrides(
										{
											iEDHklQvm: {
												y: (componentViewport?.y || 0) + 24 + 0 + 363.2 + 12,
											},
											myDAPps2s: {
												y: (componentViewport?.y || 0) + 24 + 0 + 159.2 + 12,
											},
											NkEZS5G9j: {
												y:
													(componentViewport?.y || 0) +
													24 +
													(((componentViewport?.height || 200) - 72 - 290) / 2 +
														0 +
														0) +
													0 +
													363.2 +
													12,
											},
											q4_8l_OzZ: {
												y: (componentViewport?.y || 0) + 24 + 0 + 363.2 + 12,
											},
											yBr80vEWy: {
												y: (componentViewport?.y || 0) + 24 + 0 + 159.2 + 12,
											},
											ZiUjmlMWv: {
												y:
													(componentViewport?.y || 0) +
													24 +
													(((componentViewport?.height || 200) - 72 - 290) / 2 +
														0 +
														0) +
													0 +
													363.2 +
													12,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1edeil2-container"}
										layoutDependency={layoutDependency}
										layoutId={"pwBYDFu7l-container"}
										nodeId={"pwBYDFu7l"}
										rendersWithMotion={true}
										scopeId={"MxtevI0rb"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "pwBYDFu7l",
											layoutId: "pwBYDFu7l",
											lJNtxFrg5: o9SibF6N92,
											O5tlPGRu3: "Order Now",
											variant: matchVariant("YUJ4R_SbY"),
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<motion.div
									className={"framer-1hdq9mz"}
									data-framer-name={"Pricing"}
									layoutDependency={layoutDependency}
									layoutId={"z5PvMxw87"}
								>
									<motion.div
										className={"framer-2yw0cr"}
										layoutDependency={layoutDependency}
										layoutId={"pO4pZpA_A"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-59w1v8"}
											data-framer-name={"Price - Medium"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"v2CktsGzU"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													iEDHklQvm: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-146xxk6"}
																	data-styles-preset={"OIpMKy3L7"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128)))",
																	}}
																>
																	{"/portion"}
																</motion.p>
															</React.Fragment>
														),
														text: GTORt8VJU2,
													},
													myDAPps2s: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-146xxk6"}
																	data-styles-preset={"OIpMKy3L7"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128)))",
																	}}
																>
																	{"/portion"}
																</motion.p>
															</React.Fragment>
														),
														text: GTORt8VJU2,
													},
													TaTZpoRBy: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-146xxk6"}
																	data-styles-preset={"OIpMKy3L7"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128)))",
																	}}
																>
																	{"/portion"}
																</motion.p>
															</React.Fragment>
														),
														text: GTORt8VJU2,
													},
													ZiUjmlMWv: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-146xxk6"}
																	data-styles-preset={"OIpMKy3L7"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128)))",
																	}}
																>
																	{"/portion"}
																</motion.p>
															</React.Fragment>
														),
														text: GTORt8VJU2,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-146xxk6"}
													data-styles-preset={"OIpMKy3L7"}
													dir={"auto"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128)))",
													}}
												>
													{"from"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-30fe5y"}
										data-framer-name={"Price - Medium"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"mttJbrUbS"}
										text={gWA6po3g92}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-18kbsqc"}
												data-styles-preset={"e4uTd5msu"}
												dir={"auto"}
											>
												{"$14.99"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css12 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-yeQSV.framer-wmarbb, .framer-yeQSV .framer-wmarbb { display: block; }",
	".framer-yeQSV.framer-k9wk7 { align-content: center; align-items: center; cursor: default; display: flex; flex-direction: column; flex-wrap: wrap; gap: 40px; height: min-content; justify-content: center; padding: 24px; position: relative; width: 359px; }",
	".framer-yeQSV .framer-1t6erfq { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 280px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 280px; }",
	".framer-yeQSV .framer-xuaifq { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 360px); left: 50%; position: absolute; top: -54px; width: 360px; z-index: 1; }",
	".framer-yeQSV .framer-12pieyh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; min-width: 200px; padding: 0px; position: relative; width: 100%; }",
	".framer-yeQSV .framer-13gjfch { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-yeQSV .framer-15jlfg5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; min-height: 200px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-yeQSV .framer-e9osoi, .framer-yeQSV .framer-49w3mx, .framer-yeQSV .framer-6x38hl, .framer-yeQSV .framer-30fe5y { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-yeQSV .framer-l71ek3, .framer-yeQSV .framer-1mfy7nc { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-yeQSV .framer-kii31b, .framer-yeQSV .framer-1mc3vpu { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-yeQSV .framer-1vczlyq { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 120px; word-break: break-word; word-wrap: break-word; }",
	".framer-yeQSV .framer-1f8ptlm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 12px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-yeQSV .framer-1edeil2-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-yeQSV .framer-1hdq9mz { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-yeQSV .framer-2yw0cr { align-content: flex-end; align-items: flex-end; align-self: stretch; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: auto; justify-content: center; overflow: visible; padding: 0px 0px 1px 0px; position: relative; width: min-content; }",
	".framer-yeQSV .framer-59w1v8 { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-yeQSV.framer-v-nvoup0.framer-k9wk7, .framer-yeQSV.framer-v-1lurm80.framer-k9wk7 { flex-direction: row; padding: 24px 0px 48px 0px; width: 680px; }",
	".framer-yeQSV.framer-v-nvoup0 .framer-xuaifq, .framer-yeQSV.framer-v-rydr9o .framer-xuaifq, .framer-yeQSV.framer-v-srf1oa .framer-xuaifq { height: var(--framer-aspect-ratio-supported, 280px); top: 50%; width: 280px; }",
	".framer-yeQSV.framer-v-nvoup0 .framer-12pieyh, .framer-yeQSV.framer-v-rydr9o .framer-12pieyh { flex: 1 0 0px; width: 1px; }",
	".framer-yeQSV.framer-v-nvoup0 .framer-13gjfch, .framer-yeQSV.framer-v-1pxosm6 .framer-30fe5y, .framer-yeQSV.framer-v-srf1oa .framer-30fe5y, .framer-yeQSV.framer-v-1lurm80 .framer-13gjfch, .framer-yeQSV.framer-v-1lurm80 .framer-30fe5y, .framer-yeQSV.framer-v-jaeg78 .framer-13gjfch, .framer-yeQSV.framer-v-p8wajo .framer-13gjfch, .framer-yeQSV.framer-v-p8wajo .framer-30fe5y { order: 0; }",
	".framer-yeQSV.framer-v-nvoup0 .framer-15jlfg5, .framer-yeQSV.framer-v-1lurm80 .framer-15jlfg5, .framer-yeQSV.framer-v-jaeg78 .framer-15jlfg5, .framer-yeQSV.framer-v-p8wajo .framer-15jlfg5 { min-height: unset; order: 4; }",
	".framer-yeQSV.framer-v-nvoup0 .framer-e9osoi, .framer-yeQSV.framer-v-nvoup0 .framer-6x38hl, .framer-yeQSV.framer-v-1lurm80 .framer-e9osoi, .framer-yeQSV.framer-v-1lurm80 .framer-6x38hl, .framer-yeQSV.framer-v-jaeg78 .framer-e9osoi, .framer-yeQSV.framer-v-jaeg78 .framer-6x38hl, .framer-yeQSV.framer-v-p8wajo .framer-e9osoi, .framer-yeQSV.framer-v-p8wajo .framer-6x38hl { white-space: pre-wrap; width: 120px; word-break: break-word; word-wrap: break-word; }",
	".framer-yeQSV.framer-v-nvoup0 .framer-l71ek3, .framer-yeQSV.framer-v-1lurm80 .framer-l71ek3, .framer-yeQSV.framer-v-jaeg78 .framer-l71ek3, .framer-yeQSV.framer-v-p8wajo .framer-l71ek3 { order: 3; }",
	".framer-yeQSV.framer-v-nvoup0 .framer-1mfy7nc, .framer-yeQSV.framer-v-1lurm80 .framer-1mfy7nc, .framer-yeQSV.framer-v-jaeg78 .framer-1mfy7nc, .framer-yeQSV.framer-v-p8wajo .framer-1mfy7nc { order: 2; }",
	".framer-yeQSV.framer-v-nvoup0 .framer-1f8ptlm, .framer-yeQSV.framer-v-1lurm80 .framer-1f8ptlm, .framer-yeQSV.framer-v-jaeg78 .framer-1f8ptlm, .framer-yeQSV.framer-v-p8wajo .framer-1f8ptlm { order: 7; }",
	".framer-yeQSV.framer-v-rydr9o.framer-k9wk7, .framer-yeQSV.framer-v-srf1oa.framer-k9wk7 { flex-direction: row; width: 680px; }",
	".framer-yeQSV.framer-v-rydr9o .framer-1t6erfq, .framer-yeQSV.framer-v-srf1oa .framer-1t6erfq { height: var(--framer-aspect-ratio-supported, 240px); width: 240px; }",
	".framer-yeQSV.framer-v-1pxosm6.framer-k9wk7 { width: 359px; }",
	".framer-yeQSV.framer-v-1pxosm6 .framer-1hdq9mz { gap: 4px; }",
	".framer-yeQSV.framer-v-1pxosm6 .framer-2yw0cr, .framer-yeQSV.framer-v-srf1oa .framer-2yw0cr, .framer-yeQSV.framer-v-1lurm80 .framer-2yw0cr, .framer-yeQSV.framer-v-p8wajo .framer-2yw0cr { order: 1; }",
	".framer-yeQSV.framer-v-srf1oa .framer-12pieyh, .framer-yeQSV.framer-v-1lurm80 .framer-12pieyh { align-content: flex-start; align-items: flex-start; flex: 1 0 0px; width: 1px; }",
	".framer-yeQSV.framer-v-1lurm80 .framer-1t6erfq { height: var(--framer-aspect-ratio-supported, 320px); width: 320px; }",
	".framer-yeQSV.framer-v-1lurm80 .framer-xuaifq { height: var(--framer-aspect-ratio-supported, 320px); top: 50%; width: 320px; }",
	".framer-yeQSV.framer-v-jaeg78.framer-k9wk7, .framer-yeQSV.framer-v-p8wajo.framer-k9wk7 { padding: 24px 0px 48px 0px; width: 358px; }",
	".framer-yeQSV.framer-v-jaeg78 .framer-1t6erfq, .framer-yeQSV.framer-v-p8wajo .framer-1t6erfq { height: var(--framer-aspect-ratio-supported, 290px); width: 290px; }",
	".framer-yeQSV.framer-v-jaeg78 .framer-xuaifq, .framer-yeQSV.framer-v-p8wajo .framer-xuaifq { top: 50%; }",
	".framer-yeQSV.framer-v-p8wajo .framer-12pieyh { align-content: flex-start; align-items: flex-start; }",
	...css3,
	...css5,
	...css11,
	...css8,
	...css4,
	...css9,
	...css10,
	...css7,
	...css6,
	...css2,
	...css,
	'.framer-yeQSV[data-border="true"]::after, .framer-yeQSV [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerMxtevI0rb = withCSS(Component, css12, "framer-yeQSV");
var stdin_default2 = FramerMxtevI0rb;
FramerMxtevI0rb.displayName = "Menu Products/Product Card";
FramerMxtevI0rb.defaultProps = {
	height: 513,
	width: 358,
};
addPropertyControls(FramerMxtevI0rb, {
	variant: {
		options: [
			"DnzGOsfzr",
			"q4_8l_OzZ",
			"yBr80vEWy",
			"TaTZpoRBy",
			"myDAPps2s",
			"iEDHklQvm",
			"NkEZS5G9j",
			"ZiUjmlMWv",
		],
		optionTitles: [
			"Only Pizza - Desktop",
			"Only Pizza - Menu - Desktop",
			"Only Pizza - Tablet",
			"Others - Desktop",
			"Others - Tablet",
			"Others - Menu - Desktop",
			"Only Pizza - Menu - Mobile",
			"Others - Menu - Mobile",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	EKtkBiqHP: {
		__defaultAssetReference:
			"data:framer/asset-reference,TselH8OEkb2YNE35eIM1vVAfb6s.png?originalFilename=pizza-margheritta.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	FZjwTwKXl: {
		defaultValue: "Pepperoni Popper",
		title: "Title",
		type: ControlType.String,
	},
	gWA6po3g9: {
		defaultValue: "$14.99",
		title: "Price - Medium",
		type: ControlType.String,
	},
	ZaUVK_Zrs: {
		defaultValue:
			"<p>Double pepperoni, mozzarella, spicy marinara sauce, crushed red pepper, black olives</p>",
		title: "Ingredients",
		type: ControlType.RichText,
	},
	mxkLNJQZN: {
		defaultValue: "Dairy, Gluten",
		title: "Alergen Warnings",
		type: ControlType.String,
	},
	o9SibF6N9: {
		title: "Link",
		type: ControlType.Link,
	},
	GTORt8VJU: {
		defaultValue: "/portion",
		displayTextArea: false,
		title: "Portion",
		type: ControlType.String,
	},
	JV7xTZLzb: {
		defaultValue: "<p>Nutritional Info</p>",
		title: "Content",
		type: ControlType.RichText,
	},
	JoZ2UEEJT: {
		defaultValue: "<p>Dairy, Gluten</p>",
		title: "Nutritional Info",
		type: ControlType.RichText,
	},
});
addFonts(
	FramerMxtevI0rb,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts11),
		...getFontsFromSharedStyle(fonts8),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts9),
		...getFontsFromSharedStyle(fonts10),
		...getFontsFromSharedStyle(fonts7),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerMxtevI0rb.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:menu-products/product-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "myDAPps2s",
	xl: "DnzGOsfzr",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a377177818209678b37adc5f263446ba17148664a97f412372f73ef06885d900"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProductCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a377177818209678b37adc5f263446ba17148664a97f412372f73ef06885d900"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var product_card_default = ComponentWithRoot;
export { product_card_default as default };
