process.chdir("/dev-server");
const { loadEnvFiles } = await import("/dev-server/tests/regression/lib/load-env.mjs");
loadEnvFiles();
const { chromium } = await import("playwright");
const { createClient } = await import("/dev-server/node_modules/@supabase/supabase-js/dist/module/index.js");
const { resolveAdminCredentials } = await import("/dev-server/tests/regression/lib/admin-session.mjs");
const { storageKeyFor } = await import("/dev-server/tests/regression/lib/browser-session.mjs");
const supa = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession:false, autoRefreshToken:false }});
const creds = await resolveAdminCredentials();
const { data } = await supa.auth.signInWithPassword({ email: creds.email, password: creds.password });
const b = await chromium.launch({headless:true});
const p = await (await b.newContext({viewport:{width:1280,height:900}})).newPage();
p.on("console", m => console.log("CONSOLE", m.type(), m.text().slice(0,200)));
await p.goto("http://localhost:8080/auth", {waitUntil:"domcontentloaded"});
await p.evaluate(([k,s])=>localStorage.setItem(k,JSON.stringify(s)), [storageKeyFor(process.env.SUPABASE_URL, process.env.SUPABASE_PROJECT_ID), data.session]);
await p.goto("http://localhost:8080/admin/products", {waitUntil:"domcontentloaded"});
await p.waitForTimeout(6000);
console.log("URL", p.url());
console.log((await p.locator("body").innerText()).slice(0,800));
await b.close();
