import { loadEnvFiles } from "./lib/load-env.mjs";
loadEnvFiles();
import { chromium } from "playwright";
import { createClient } from "@supabase/supabase-js";
import { createEphemeralCustomerSession } from "./lib/browser-session.mjs";
const url=process.env.SUPABASE_URL, pk=process.env.SUPABASE_PUBLISHABLE_KEY, sr=process.env.SUPABASE_SERVICE_ROLE_KEY;
const sess = await createEphemeralCustomerSession({supabaseUrl:url, serviceRoleKey:sr, publishableKey:pk, projectId:process.env.SUPABASE_PROJECT_ID, emailPrefix:"regr-dbg"});
const b = await chromium.launch({headless:true});
const p = await (await b.newContext({viewport:{width:1280,height:900}})).newPage();
p.on("console", m=>{const t=m.text(); if(/realtime|channel|SUBSCRIB|error|fingerprint/i.test(t)) console.log("C:", t.slice(0,200));});
await p.goto("http://localhost:8080/auth",{waitUntil:"domcontentloaded"});
await p.evaluate(([k,s])=>localStorage.setItem(k,JSON.stringify(s)),[sess.storageKey,sess.session]);
await p.goto("http://localhost:8080/",{waitUntil:"domcontentloaded"});
await p.waitForTimeout(4000);
const admin = createClient(url, sr, {auth:{persistSession:false}});
const { data: prod } = await admin.from("products").select("id,title").eq("is_active",true).limit(1).single();
await admin.from("products").update({title: prod.title+" DBG"}).eq("id",prod.id);
console.log("updated", prod.title);
await p.waitForTimeout(8000);
console.log("banner visible:", await p.getByTestId("home-content-update-banner").isVisible().catch(()=>false));
await admin.from("products").update({title: prod.title}).eq("id",prod.id);
await b.close(); await sess.cleanup();
