// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5352a114c0b2f653 "Pepper (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Mobile' // Variant
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-JEA7JOIB.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-36E3MYEK.js";
import { stdin_default } from "../chunks/chunk-HLWZXJZG.js";
import { routes } from "../chunks/chunk-H6F5WHVF.js";

// virtual:newsletter/newsletter
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/850lL92iPEJibzNmaOBD/Ekfr0lcptNdVamnIiDBF/kXgL_bm9N.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType,
	cx as cx2,
	forwardLoader as forwardLoader2,
	getFonts as getFonts2,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/29o6q5D2Z8FGAAmFYM6e/OECRFX5M25CrxR8BFtyg/qPUB_hqyc.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	FormContainer,
	FormPlainTextInput,
	forwardLoader,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ButtonFormFonts = getFonts(stdin_default);
var serializationHash = "framer-MoRVX";
var variantClassNames = {
	MsyWt7JGR: "framer-v-87fnn0",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var formVariants = (form, variants, currentVariant) => {
	switch (form.state) {
		case "success":
			return variants.success ?? currentVariant;
		case "pending":
			return variants.pending ?? currentVariant;
		case "error":
			return variants.error ?? currentVariant;
		case "incomplete":
			return variants.incomplete ?? currentVariant;
		default:
			return currentVariant;
	}
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "MsyWt7JGR",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<FormContainer
						{...restProps}
						{...gestureHandlers}
						action={
							"https://api.framer.com/forms/v1/forms/de9df00c-d321-4e5a-8b00-f673d2dbb0e9/submit"
						}
						className={cx(
							scopingClassNames,
							"framer-87fnn0",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"MsyWt7JGR"}
						nodeId={"MsyWt7JGR"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						{(formState) => (
							<_Fragment>
								<motion.label
									className={"framer-mpvhcy"}
									layoutDependency={layoutDependency}
									layoutId={"B7ier5ffW"}
								>
									<FormPlainTextInput
										className={"framer-1rhlcuy"}
										inputName={"Email"}
										layoutDependency={layoutDependency}
										layoutId={"kcqFI7Ia2"}
										placeholder={"youremail@email.com"}
										required={true}
										style={{
											"--framer-input-background":
												"var(--token-e63bc84a-87bd-415d-9b16-445dc312962c, rgb(250, 250, 250))",
											"--framer-input-border-bottom-width": "1px",
											"--framer-input-border-color": "rgba(136, 136, 136, 0.1)",
											"--framer-input-border-left-width": "1px",
											"--framer-input-border-radius-bottom-left": "27px",
											"--framer-input-border-radius-bottom-right": "27px",
											"--framer-input-border-radius-top-left": "27px",
											"--framer-input-border-radius-top-right": "27px",
											"--framer-input-border-right-width": "1px",
											"--framer-input-border-style": "solid",
											"--framer-input-border-top-width": "1px",
											"--framer-input-font-color":
												"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51))",
											"--framer-input-icon-color": "rgb(153, 153, 153)",
											"--framer-input-placeholder-color":
												"var(--token-b2e77e9c-88d2-44f3-86e9-0b57b23b663f, rgb(128, 128, 128))",
										}}
										type={"email"}
									/>
								</motion.label>
								<ComponentViewportProvider
									height={48}
									width={componentViewport?.width || "100vw"}
									y={(componentViewport?.y || 0) + 0 + 72}
								>
									<SmartComponentScopedContainer
										className={"framer-1lb9666-container"}
										layoutDependency={layoutDependency}
										layoutId={"GJEfIUJ_d-container"}
										nodeId={"GJEfIUJ_d"}
										rendersWithMotion={true}
										scopeId={"qPUB_hqyc"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "GJEfIUJ_d",
											layoutId: "GJEfIUJ_d",
											style: {
												width: "100%",
											},
											type: "submit",
											variant: formVariants(
												formState,
												{
													pending: "UUDmxBpbn",
													success: "edoZVqWvl",
												},
												matchVariant("nYLI2tEax"),
											),
											width: "100%",
											Zej6Dkc0D: "Submit",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</_Fragment>
						)}
					</FormContainer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-MoRVX.framer-1qgv755, .framer-MoRVX .framer-1qgv755 { display: block; }",
	".framer-MoRVX.framer-87fnn0 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 413px; }",
	".framer-MoRVX .framer-mpvhcy { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	'.framer-MoRVX .framer-1rhlcuy { --framer-input-focused-border-color: var(--token-7e4c7b4f-c1ce-4b49-afda-09aa102c67c0, #0080ff); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "Inter"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 14px; --framer-input-font-weight: 400; --framer-input-padding: 20px; flex: none; height: 48px; position: relative; width: 100%; }',
	".framer-MoRVX .framer-1lb9666-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var FramerqPUB_hqyc = withCSS(Component, css3, "framer-MoRVX");
var stdin_default2 = FramerqPUB_hqyc;
FramerqPUB_hqyc.displayName = "Newsletter/Form - Newsletter";
FramerqPUB_hqyc.defaultProps = {
	height: 120,
	width: 413,
};
addFonts(
	FramerqPUB_hqyc,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "google",
					style: "normal",
					uiFamilyName: "Inter",
					url: "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuLyfMZ1rib2Bg-4.woff2",
					weight: "400",
				},
			],
		},
		...ButtonFormFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerqPUB_hqyc.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// /:https://framerusercontent.com/modules/850lL92iPEJibzNmaOBD/Ekfr0lcptNdVamnIiDBF/kXgL_bm9N.js
var ImageWithFX = withFX(Image);
var NewsletterFormNewsletterFonts = getFonts2(stdin_default2);
var cycleOrder = ["UuqDYUOz6", "oZN6tn8M5", "P7Ej81AbH"];
var serializationHash2 = "framer-yGJu3";
var variantClassNames2 = {
	oZN6tn8M5: "framer-v-wqi5ed",
	P7Ej81AbH: "framer-v-99y581",
	UuqDYUOz6: "framer-v-1qov1ou",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 240,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "UuqDYUOz6",
	Mobile: "P7Ej81AbH",
	Tablet: "oZN6tn8M5",
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "UuqDYUOz6",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "UuqDYUOz6",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1qov1ou",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"UuqDYUOz6"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								oZN6tn8M5: {
									"data-framer-name": "Tablet",
								},
								P7Ej81AbH: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-11z4aqz"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"i24TN0lAP"}
						>
							<motion2.div
								className={"framer-p8z7o5"}
								data-framer-name={"Pizza Stack"}
								layoutDependency={layoutDependency}
								layoutId={"SYmGJ2S8N"}
							>
								<ImageWithFX
									__framer__loop={animation}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition2}
									__framer__styleTransformEffectEnabled={true}
									__framer__transformTargets={[
										{
											target: {
												opacity: 1,
												rotate: 0,
												rotateX: 0,
												rotateY: 0,
												scale: 1,
												skewX: 0,
												skewY: 0,
												x: 0,
												y: 0,
											},
										},
										{
											target: {
												opacity: 1,
												rotate: 90,
												rotateX: 0,
												rotateY: 0,
												scale: 1,
												skewX: 0,
												skewY: 0,
												x: 0,
												y: 0,
											},
										},
									]}
									__framer__transformTrigger={"onScroll"}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									background={{
										alt: "Pizza Margheritta",
										fit: "fill",
										intrinsicHeight: 512,
										intrinsicWidth: 512,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												(80 +
													((componentViewport?.height || 200) - 160 - 368) /
														2) +
												0 +
												-48,
										),
										pixelHeight: 1024,
										pixelWidth: 1024,
										sizes: "464px",
										src: "https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?width=1024&height=1024",
										srcSet:
											"https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?width=1024&height=1024 1024w",
									}}
									className={"framer-1bzvn1v"}
									data-framer-name={"pepperoni_pizza"}
									layoutDependency={layoutDependency}
									layoutId={"kaYmeRIQ5"}
									transformTemplate={transformTemplate1}
									{...addPropertyOverrides(
										{
											oZN6tn8M5: {
												background: {
													alt: "Pizza Margheritta",
													fit: "fill",
													intrinsicHeight: 512,
													intrinsicWidth: 512,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	160 -
																	368) /
																	2) +
															0 +
															12,
													),
													pixelHeight: 1024,
													pixelWidth: 1024,
													sizes: "344px",
													src: "https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?width=1024&height=1024",
													srcSet:
														"https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?width=1024&height=1024 1024w",
												},
											},
											P7Ej81AbH: {
												background: {
													alt: "Pizza Margheritta",
													fit: "fill",
													intrinsicHeight: 512,
													intrinsicWidth: 512,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															80 +
															(((componentViewport?.height || 200) -
																160 -
																820) /
																2 +
																0 +
																0) +
															0 +
															392 +
															0,
													),
													pixelHeight: 1024,
													pixelWidth: 1024,
													sizes: "428px",
													src: "https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?width=1024&height=1024",
													srcSet:
														"https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/TselH8OEkb2YNE35eIM1vVAfb6s.png?width=1024&height=1024 1024w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion2.div>
							<motion2.header
								className={"framer-k862ye"}
								data-framer-name={"Header"}
								layoutDependency={layoutDependency}
								layoutId={"PM3MpRESK"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-hmu1qu"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Yr0JzRtts"}
									style={{
										"--extracted-1of0zx5":
											"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											P7Ej81AbH: {
												children: (
													<React2.Fragment>
														<motion2.h2
															className={"framer-styles-preset-a7kjrb"}
															data-styles-preset={"oSwZ59yDX"}
															style={{
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-1of0zx5, var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51)))",
															}}
														>
															{"Delicious Deals,"}
															<motion2.br />
															{"Just for You"}
														</motion2.h2>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.h2
											className={"framer-styles-preset-a7kjrb"}
											data-styles-preset={"oSwZ59yDX"}
											dir={"auto"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-1of0zx5, var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51)))",
											}}
										>
											{"Delicious Deals, Just for You"}
										</motion2.h2>
									</React2.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1lessqs"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"JU0oDyo_r"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(26, 26, 26))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											P7Ej81AbH: {
												children: (
													<React2.Fragment>
														<motion2.p
															className={"framer-styles-preset-1bh5kbf"}
															data-styles-preset={"jBpmYi8dY"}
															dir={"auto"}
															style={{
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(26, 26, 26)))",
															}}
														>
															{
																"Sign up for our newsletter and receive exclusive offers on new pizzas!"
															}
														</motion2.p>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1bh5kbf"}
											data-styles-preset={"jBpmYi8dY"}
											dir={"auto"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(26, 26, 26)))",
											}}
										>
											{
												"Sign up for our newsletter and receive exclusive offers on new pizzas!"
											}
										</motion2.p>
									</React2.Fragment>
								</RichText>
								<ComponentViewportProvider2
									height={120}
									width={`max((min(max(${componentViewport?.width || "100vw"} - 48px, 1px), 1200px) - 24px) / 2, 1px)`}
									y={
										(componentViewport?.y || 0) +
										(80 +
											((componentViewport?.height || 200) - 160 - 368) / 2) +
										0 +
										0 +
										248
									}
									{...addPropertyOverrides(
										{
											P7Ej81AbH: {
												width: `min(${componentViewport?.width || "100vw"} - 48px, 1200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 200) - 160 - 820) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													248,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-teu5ua-container"}
										layoutDependency={layoutDependency}
										layoutId={"iPTaJsEdU-container"}
										nodeId={"iPTaJsEdU"}
										rendersWithMotion={true}
										scopeId={"kXgL_bm9N"}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "iPTaJsEdU",
											layoutId: "iPTaJsEdU",
											style: {
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</motion2.header>
						</motion2.div>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-yGJu3.framer-3t3e36, .framer-yGJu3 .framer-3t3e36 { display: block; }",
	".framer-yGJu3.framer-1qov1ou { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 80px 24px 80px 24px; position: relative; width: 1200px; }",
	".framer-yGJu3 .framer-11z4aqz { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-yGJu3 .framer-p8z7o5 { align-content: center; align-items: center; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: auto; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-yGJu3 .framer-1bzvn1v { aspect-ratio: 1 / 1; bottom: -48px; flex: none; left: 50%; overflow: visible; position: absolute; top: -48px; width: var(--framer-aspect-ratio-supported, 413px); z-index: 1; }",
	".framer-yGJu3 .framer-k862ye { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; z-index: 2; }",
	".framer-yGJu3 .framer-hmu1qu { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 440px; word-break: break-word; word-wrap: break-word; }",
	".framer-yGJu3 .framer-1lessqs { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 400px; word-break: break-word; word-wrap: break-word; }",
	".framer-yGJu3 .framer-teu5ua-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-yGJu3.framer-v-wqi5ed.framer-1qov1ou { width: 810px; }",
	".framer-yGJu3.framer-v-wqi5ed .framer-1bzvn1v { bottom: 12px; left: 50%; top: 12px; width: var(--framer-aspect-ratio-supported, 416px); }",
	".framer-yGJu3.framer-v-wqi5ed .framer-hmu1qu, .framer-yGJu3.framer-v-wqi5ed .framer-1lessqs, .framer-yGJu3.framer-v-99y581 .framer-hmu1qu, .framer-yGJu3.framer-v-99y581 .framer-1lessqs { width: 100%; }",
	".framer-yGJu3.framer-v-99y581.framer-1qov1ou { flex-direction: column; width: 390px; }",
	".framer-yGJu3.framer-v-99y581 .framer-11z4aqz { flex: none; flex-direction: column; width: 100%; }",
	".framer-yGJu3.framer-v-99y581 .framer-p8z7o5 { align-self: unset; flex: none; height: 428px; order: 1; width: 100%; }",
	".framer-yGJu3.framer-v-99y581 .framer-1bzvn1v { bottom: 0px; left: 50%; top: 0px; width: var(--framer-aspect-ratio-supported, 476px); }",
	".framer-yGJu3.framer-v-99y581 .framer-k862ye { flex: none; order: 0; width: 100%; }",
	...css,
	...css2,
];
var FramerkXgL_bm9N = withCSS2(Component2, css4, "framer-yGJu3");
var stdin_default3 = FramerkXgL_bm9N;
FramerkXgL_bm9N.displayName = "Newsletter/Newsletter";
FramerkXgL_bm9N.defaultProps = {
	height: 512,
	width: 1200,
};
addPropertyControls(FramerkXgL_bm9N, {
	variant: {
		options: ["UuqDYUOz6", "oZN6tn8M5", "P7Ej81AbH"],
		optionTitles: ["Desktop", "Tablet", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts2(
	FramerkXgL_bm9N,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...NewsletterFormNewsletterFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerkXgL_bm9N.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader2(stdin_default2, {}, context)]);
	},
};

// virtual:newsletter/newsletter
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5352a114c0b2f6533408ce29eda21dd74155cc4d0edaebe1b159ba55a597a9fd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NewsletterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5352a114c0b2f6533408ce29eda21dd74155cc4d0edaebe1b159ba55a597a9fd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var newsletter_default = ComponentWithRoot;
export { newsletter_default as default };
