// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a377177818209678 "Pepper (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Mobile - Default' | 'Mobile - Default - Open' // Variant
}} Props

 */
import { stdin_default } from "../chunks/chunk-RGEGD6RN.js";
import { className, css, fonts } from "../chunks/chunk-U7XD74U4.js";
import { routes } from "../chunks/chunk-H6F5WHVF.js";

// virtual:top-nav/nav
import { Fragment as Fragment5 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qYXrhd0d6T5I1vfkN9S1/RMrkQA0Q3jzQvBtKt2DQ/dZlNTDru2.js
import { jsx as _jsx5, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addFonts as addFonts4,
	addPropertyControls as addPropertyControls5,
	ComponentViewportProvider,
	ControlType as ControlType5,
	cx as cx4,
	getFonts,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback3,
	useComponentViewport as useComponentViewport4,
	useLocaleInfo as useLocaleInfo4,
	useRouter,
	useVariantState as useVariantState4,
	withCSS as withCSS4,
	withFX as withFX2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup4,
	motion as motion4,
	MotionConfigContext as MotionConfigContext4,
} from "unframer";
import * as React4 from "react";
import { useRef as useRef4 } from "react";

// /:https://framerusercontent.com/modules/9ajhXMTvNHa3o84QkAph/PbD4QdXIvghwk9ZrKeou/StopScroll_Prod.js
import { jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
function StopScroll(props) {
	const { toggle } = props;
	return toggle ? (
		<style
			data-frameruni-stop-scroll={true}
		>{`html,body { overflow: hidden !important; }`}</style>
	) : (
		<_Fragment />
	);
}
StopScroll.displayName = "Stop Scroll";
addPropertyControls(StopScroll, {
	toggle: {
		type: ControlType.Boolean,
		title: "Block Scroll",
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
	},
});

// /:https://framerusercontent.com/modules/kMscPm4zq02G233JoOU2/aP2U7QcNPfoHSl1IlTHk/i_d3uwhLb.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["RYIK1jVXm", "HYqfBQCDM"];
var serializationHash = "framer-s4nf5";
var variantClassNames = {
	HYqfBQCDM: "framer-v-19ha1fy",
	RYIK1jVXm: "framer-v-hegwbc",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Close: "HYqfBQCDM",
	Default: "RYIK1jVXm",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "RYIK1jVXm",
		XPTlw43ck: click ?? props.XPTlw43ck,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		XPTlw43ck: XPTlw43ck2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "RYIK1jVXm",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapx7rgkg = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (XPTlw43ck2) {
			const res = await XPTlw43ck2(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-hegwbc",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"RYIK1jVXm"}
						onTap={onTapx7rgkg}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								HYqfBQCDM: {
									"data-framer-name": "Close",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1ijx2nt"}
							layoutDependency={layoutDependency}
							layoutId={"g2IR8yd2S"}
							style={{
								backgroundColor:
									"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51))",
								borderBottomLeftRadius: 1,
								borderBottomRightRadius: 1,
								borderTopLeftRadius: 1,
								borderTopRightRadius: 1,
								rotate: 0,
							}}
							variants={{
								HYqfBQCDM: {
									rotate: -45,
								},
							}}
						/>
						<motion.div
							className={"framer-unux86"}
							layoutDependency={layoutDependency}
							layoutId={"aUn2bvdkh"}
							style={{
								backgroundColor:
									"var(--token-87e6d356-f892-4c3e-bd6c-68461b752930, rgb(51, 51, 51))",
								borderBottomLeftRadius: 1,
								borderBottomRightRadius: 1,
								borderTopLeftRadius: 1,
								borderTopRightRadius: 1,
								rotate: 0,
							}}
							variants={{
								HYqfBQCDM: {
									rotate: 45,
								},
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-s4nf5.framer-1irz6kn, .framer-s4nf5 .framer-1irz6kn { display: block; }",
	".framer-s4nf5.framer-hegwbc { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: 24px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 24px; }",
	".framer-s4nf5 .framer-1ijx2nt { flex: none; height: 1px; left: calc(50.00000000000002% - 24px / 2); overflow: hidden; position: absolute; top: 7px; width: 24px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-s4nf5 .framer-unux86 { bottom: 7px; flex: none; height: 1px; left: calc(50.00000000000002% - 24px / 2); overflow: hidden; position: absolute; width: 24px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-s4nf5.framer-v-19ha1fy .framer-1ijx2nt { top: 12px; }",
	".framer-s4nf5.framer-v-19ha1fy .framer-unux86 { bottom: unset; top: calc(50.00000000000002% - 1px / 2); }",
];
var Frameri_d3uwhLb = withCSS(Component, css2, "framer-s4nf5");
var stdin_default2 = Frameri_d3uwhLb;
Frameri_d3uwhLb.displayName = "Top Nav/Hamburger Menu";
Frameri_d3uwhLb.defaultProps = {
	height: 24,
	width: 24,
};
addPropertyControls2(Frameri_d3uwhLb, {
	variant: {
		options: ["RYIK1jVXm", "HYqfBQCDM"],
		optionTitles: ["Default", "Close"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	XPTlw43ck: {
		title: "Click",
		type: ControlType2.EventHandler,
	},
});
addFonts(
	Frameri_d3uwhLb,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/zzA5PYR4Gom2P3ALPqvM/9ij5IOLhsC8W9lCAwSO8/k9L1wxZoZ.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
	cx as cx2,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";
var MotionDivWithFX = withFX(motion2.div);
var enabledGestures = {
	V_9sojbwT: {
		hover: true,
	},
};
var cycleOrder2 = ["V_9sojbwT", "UubYA4zgr"];
var serializationHash2 = "framer-Ku4wf";
var variantClassNames2 = {
	UubYA4zgr: "framer-v-1cwqnue",
	V_9sojbwT: "framer-v-fgwk78",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var transition2 = {
	delay: 0,
	duration: 4,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 6,
};
var transition3 = {
	delay: 0,
	duration: 3,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var transition4 = {
	delay: 0,
	duration: 2,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var transition5 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1.02,
	skewX: 0,
	skewY: 0,
	transition: transition5,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableVariantMap2 = {
	"Checked - Only Mobile": "UubYA4zgr",
	Default: "V_9sojbwT",
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ click, height, id, link, title, width, ...props }) => {
	return {
		...props,
		dAlYioEwr: click ?? props.dAlYioEwr,
		o44erva5E: title ?? props.o44erva5E ?? "Pizza",
		rS0NYgfTL: link ?? props.rS0NYgfTL,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "V_9sojbwT",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		o44erva5E: o44erva5E2,
		rS0NYgfTL: rS0NYgfTL2,
		dAlYioEwr: dAlYioEwr2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "V_9sojbwT",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const onTapfaq8y4 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (dAlYioEwr2) {
			const res = await dAlYioEwr2(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<Link
						href={rS0NYgfTL2}
						motionChild={true}
						nodeId={"V_9sojbwT"}
						scopeId={"k9L1wxZoZ"}
					>
						<motion2.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx2(scopingClassNames, "framer-fgwk78", className2, classNames)} framer-1em4047`}
							data-framer-name={"Default"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"V_9sojbwT"}
							onTap={onTapfaq8y4}
							ref={refBinding}
							style={{
								backgroundColor: "rgba(0, 0, 0, 0)",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
								...style,
							}}
							variants={{
								"V_9sojbwT-hover": {
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
								UubYA4zgr: {
									backgroundColor:
										"var(--token-e63bc84a-87bd-415d-9b16-445dc312962c, rgb(250, 250, 250))",
								},
							}}
							{...addPropertyOverrides2(
								{
									"V_9sojbwT-hover": {
										"data-framer-name": void 0,
									},
									UubYA4zgr: {
										"data-framer-name": "Checked - Only Mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<MotionDivWithFX
								className={"framer-1778zmc"}
								data-framer-name={"Bullet"}
								layoutDependency={layoutDependency}
								layoutId={"fEg63A_RA"}
								style={{
									backgroundColor:
										"var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 153, 0))",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
								transformTemplate={transformTemplate1}
								{...addPropertyOverrides2(
									{
										"V_9sojbwT-hover": {
											__framer__loop: animation,
											__framer__loopEffectEnabled: true,
											__framer__loopRepeatDelay: 0,
											__framer__loopRepeatType: "mirror",
											__framer__loopTransition: transition2,
											__perspectiveFX: false,
											__smartComponentFX: true,
											__targetOpacity: 1,
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<MotionDivWithFX
								className={"framer-1qxcwlq"}
								data-framer-name={"Bullet"}
								layoutDependency={layoutDependency}
								layoutId={"LKbSwySE7"}
								style={{
									backgroundColor:
										"var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 153, 0))",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
								transformTemplate={transformTemplate1}
								{...addPropertyOverrides2(
									{
										"V_9sojbwT-hover": {
											__framer__loop: animation,
											__framer__loopEffectEnabled: true,
											__framer__loopRepeatDelay: 0,
											__framer__loopRepeatType: "mirror",
											__framer__loopTransition: transition3,
											__perspectiveFX: false,
											__smartComponentFX: true,
											__targetOpacity: 1,
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<MotionDivWithFX
								className={"framer-4rc8tz"}
								data-framer-name={"Bullet"}
								layoutDependency={layoutDependency}
								layoutId={"qm8Vv52TQ"}
								style={{
									backgroundColor:
										"var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 153, 0))",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
								transformTemplate={transformTemplate1}
								{...addPropertyOverrides2(
									{
										"V_9sojbwT-hover": {
											__framer__loop: animation,
											__framer__loopEffectEnabled: true,
											__framer__loopRepeatDelay: 0,
											__framer__loopRepeatType: "mirror",
											__framer__loopTransition: transition4,
											__perspectiveFX: false,
											__smartComponentFX: true,
											__targetOpacity: 1,
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<motion2.div
								className={"framer-jogz1w"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"j_oJuQ8MY"}
								style={{
									backgroundColor:
										"var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255))",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
								variants={{
									UubYA4zgr: {
										backgroundColor:
											"var(--token-e63bc84a-87bd-415d-9b16-445dc312962c, rgb(250, 250, 250))",
									},
								}}
								whileHover={animation1}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1nyd4cu"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"yKDnA6__b"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={o44erva5E2}
									variants={{
										"V_9sojbwT-hover": {
											"--extracted-r6o4lv":
												"var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 153, 0))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides2(
										{
											"V_9sojbwT-hover": {
												children: (
													<React2.Fragment>
														<motion2.p
															className={"framer-styles-preset-ctw6nh"}
															data-styles-preset={"qnHYitKoE"}
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 153, 0)))",
															}}
														>
															{"Pizza"}
														</motion2.p>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-ctw6nh"}
											data-styles-preset={"qnHYitKoE"}
											dir={"auto"}
										>
											{"Pizza"}
										</motion2.p>
									</React2.Fragment>
								</RichText>
							</motion2.div>
						</motion2.a>
					</Link>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Ku4wf.framer-1em4047, .framer-Ku4wf .framer-1em4047 { display: block; }",
	".framer-Ku4wf.framer-fgwk78 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: 32px; justify-content: center; overflow: visible; padding: 0px 24px 0px 24px; position: relative; text-decoration: none; width: min-content; }",
	".framer-Ku4wf .framer-1778zmc { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 10px); left: 51%; overflow: hidden; position: absolute; top: 50%; width: 10px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-Ku4wf .framer-1qxcwlq { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 8px); left: 51%; overflow: hidden; position: absolute; top: 50%; width: 8px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-Ku4wf .framer-4rc8tz { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 6px); left: 51%; overflow: hidden; position: absolute; top: 50%; width: 6px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-Ku4wf .framer-jogz1w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; will-change: var(--framer-will-change-effect-override, transform); z-index: 1; }",
	".framer-Ku4wf .framer-1nyd4cu { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-Ku4wf.framer-v-fgwk78.hover .framer-1778zmc { bottom: 6px; left: 0px; top: unset; }",
	".framer-Ku4wf.framer-v-fgwk78.hover .framer-1qxcwlq { bottom: -4px; left: unset; right: 8px; top: unset; }",
	".framer-Ku4wf.framer-v-fgwk78.hover .framer-4rc8tz { left: unset; right: 32px; top: -12px; }",
	...css,
];
var Framerk9L1wxZoZ = withCSS2(Component2, css3, "framer-Ku4wf");
var stdin_default3 = Framerk9L1wxZoZ;
Framerk9L1wxZoZ.displayName = "Top Nav/Menu Link";
Framerk9L1wxZoZ.defaultProps = {
	height: 32,
	width: 89,
};
addPropertyControls3(Framerk9L1wxZoZ, {
	variant: {
		options: ["V_9sojbwT", "UubYA4zgr"],
		optionTitles: ["Default", "Checked - Only Mobile"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	o44erva5E: {
		defaultValue: "Pizza",
		displayTextArea: false,
		title: "Title",
		type: ControlType3.String,
	},
	rS0NYgfTL: {
		title: "Link",
		type: ControlType3.Link,
	},
	dAlYioEwr: {
		title: "Click",
		type: ControlType3.EventHandler,
	},
});
addFonts2(
	Framerk9L1wxZoZ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/AkH4UAwDHRJyKVzRCveq/7W1aDKTxDnZigcnJQCCV/p__Tq2YT2.js
import { jsx as _jsx4 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls4,
	ControlType as ControlType4,
	cx as cx3,
	Link as Link2,
	RichText as RichText2,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";
var cycleOrder3 = ["iixom5SgH", "kBZLZdILh"];
var serializationHash3 = "framer-8x6WV";
var variantClassNames3 = {
	iixom5SgH: "framer-v-4ztssu",
	kBZLZdILh: "framer-v-4hm7yd",
};
function addPropertyOverrides3(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition13 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var humanReadableVariantMap3 = {
	Default: "iixom5SgH",
	Negative: "kBZLZdILh",
};
var Variants3 = motion3.create(React3.Fragment);
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap3[props.variant] ?? props.variant ?? "iixom5SgH",
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder3,
		defaultVariant: "iixom5SgH",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<Link2
						href={{
							webPageId: "augiA20Il",
						}}
						motionChild={true}
						nodeId={"iixom5SgH"}
						scopeId={"p__Tq2YT2"}
					>
						<motion3.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx3(scopingClassNames, "framer-4ztssu", className2, classNames)} framer-ug7q0i`}
							data-framer-name={"Default"}
							layoutDependency={layoutDependency}
							layoutId={"iixom5SgH"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides3(
								{
									kBZLZdILh: {
										"data-framer-name": "Negative",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-323bah"}
								fonts={["GF;Cherry Bomb One-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"q8lFNQjh3"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 153, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								variants={{
									kBZLZdILh: {
										"--extracted-r6o4lv":
											"var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides3(
									{
										kBZLZdILh: {
											children: (
												<React3.Fragment>
													<motion3.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7Q2hlcnJ5IEJvbWIgT25lLXJlZ3VsYXI=",
															"--framer-font-family":
																'"Cherry Bomb One", sans-serif',
															"--framer-font-size": "36px",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255)))",
														}}
													>
														{"Pepper"}
													</motion3.p>
												</React3.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React3.Fragment>
									<motion3.p
										dir={"auto"}
										style={{
											"--font-selector": "R0Y7Q2hlcnJ5IEJvbWIgT25lLXJlZ3VsYXI=",
											"--framer-font-family": '"Cherry Bomb One", sans-serif',
											"--framer-font-size": "36px",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-1460a2d2-639e-48c8-aee5-96e4ffb1e8ff, rgb(255, 153, 0)))",
										}}
									>
										{"Pepper"}
									</motion3.p>
								</React3.Fragment>
							</RichText2>
						</motion3.a>
					</Link2>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8x6WV.framer-ug7q0i, .framer-8x6WV .framer-ug7q0i { display: block; }",
	".framer-8x6WV.framer-4ztssu { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: 54px; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-8x6WV .framer-323bah { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
];
var Framerp__Tq2YT2 = withCSS3(Component3, css4, "framer-8x6WV");
var stdin_default4 = Framerp__Tq2YT2;
Framerp__Tq2YT2.displayName = "Top Nav/Logo";
Framerp__Tq2YT2.defaultProps = {
	height: 54,
	width: 117,
};
addPropertyControls4(Framerp__Tq2YT2, {
	variant: {
		options: ["iixom5SgH", "kBZLZdILh"],
		optionTitles: ["Default", "Negative"],
		title: "Variant",
		type: ControlType4.Enum,
	},
});
addFonts3(
	Framerp__Tq2YT2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Cherry Bomb One",
					source: "google",
					style: "normal",
					uiFamilyName: "Cherry Bomb One",
					url: "https://fonts.gstatic.com/s/cherrybombone/v11/y83DW4od1h6KlV3c6JJhRhGOdhrKCdpF41fr-w.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/qYXrhd0d6T5I1vfkN9S1/RMrkQA0Q3jzQvBtKt2DQ/dZlNTDru2.js
var StopScrollFonts = getFonts(StopScroll);
var TopNavLogoFonts = getFonts(stdin_default4);
var TopNavHamburgerMenuFonts = getFonts(stdin_default2);
var TopNavMenuLinkFonts = getFonts(stdin_default3);
var ButtonFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX2(
	SmartComponentScopedContainer,
);
var cycleOrder4 = ["MkphMAJee", "DlFmeIds8", "IXlphbIvm", "zB6OLzsMr"];
var serializationHash4 = "framer-QVcdd";
var variantClassNames4 = {
	DlFmeIds8: "framer-v-16mby3w",
	IXlphbIvm: "framer-v-10sgyh6",
	MkphMAJee: "framer-v-pv0et4",
	zB6OLzsMr: "framer-v-1ii5ebr",
};
function addPropertyOverrides4(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition14 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate12 = (_, t) => `translate(-50%, -50%) ${t}`;
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition22 = {
	damping: 30,
	delay: 0.2,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var Transition4 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext4);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext4.Provider value={contextValue}>
			{children}
		</MotionConfigContext4.Provider>
	);
};
var Variants4 = motion4.create(React4.Fragment);
var humanReadableVariantMap4 = {
	"Mobile - Default - Open": "zB6OLzsMr",
	"Mobile - Default": "IXlphbIvm",
	Desktop: "MkphMAJee",
	Tablet: "DlFmeIds8",
};
var getProps4 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap4[props.variant] ?? props.variant ?? "MkphMAJee",
	};
};
var createLayoutDependency4 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef4(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo4();
	const componentViewport = useComponentViewport4();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps4(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState4({
		cycleOrder: cycleOrder4,
		defaultVariant: "MkphMAJee",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames4,
	});
	const layoutDependency = createLayoutDependency4(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback3(baseVariant);
	const XPTlw43ck1vz6xnz = activeVariantCallback(async (...args) => {
		setVariant("zB6OLzsMr");
	});
	const XPTlw43ck2x5569 = activeVariantCallback(async (...args) => {
		setVariant("IXlphbIvm");
	});
	const dAlYioEwr2x5569 = activeVariantCallback(async (...args) => {
		setVariant("IXlphbIvm");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx4(serializationHash4, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "zB6OLzsMr") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["IXlphbIvm", "zB6OLzsMr"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "IXlphbIvm") return false;
		return true;
	};
	const router = useRouter();
	return (
		<LayoutGroup4 id={layoutId ?? defaultLayoutId}>
			<Variants4 animate={variants} initial={false}>
				<Transition4 value={transition14}>
					<motion4.nav
						{...restProps}
						{...gestureHandlers}
						className={cx4(
							scopingClassNames,
							"framer-pv0et4",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"MkphMAJee"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-c53bc032-a445-44bf-b542-b566e1c9486a, rgb(255, 255, 255))",
							...style,
						}}
						{...addPropertyOverrides4(
							{
								DlFmeIds8: {
									"data-framer-name": "Tablet",
								},
								IXlphbIvm: {
									"data-framer-name": "Mobile - Default",
								},
								zB6OLzsMr: {
									"data-framer-name": "Mobile - Default - Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-khgfmz-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"locAN1da9-container"}
									nodeId={"locAN1da9"}
									rendersWithMotion={true}
									scopeId={"dZlNTDru2"}
									transformTemplate={transformTemplate12}
								>
									<StopScroll
										height={"100%"}
										id={"locAN1da9"}
										layoutId={"locAN1da9"}
										toggle={false}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						<motion4.div
							className={"framer-3cyhl6"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"TrrXwaxgA"}
						>
							<motion4.div
								className={"framer-1i58zly"}
								data-framer-name={"Logo Stack"}
								layoutDependency={layoutDependency}
								layoutId={"u0Fn6vAOX"}
							>
								<ComponentViewportProvider
									height={54}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 80) - 0 - 54) / 2) +
										0 +
										0
									}
									{...addPropertyOverrides4(
										{
											zB6OLzsMr: {
												y: (componentViewport?.y || 0) + 13 + 0 + 0 + 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-ub547f-container"}
										layoutDependency={layoutDependency}
										layoutId={"giottOuwD-container"}
										nodeId={"giottOuwD"}
										rendersWithMotion={true}
										scopeId={"dZlNTDru2"}
									>
										{_jsx5(stdin_default4, {
											height: "100%",
											id: "giottOuwD",
											layoutId: "giottOuwD",
											variant: "iixom5SgH",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								{isDisplayed1() && (
									<ComponentViewportProvider
										{...addPropertyOverrides4(
											{
												IXlphbIvm: {
													height: 24,
													width: "24px",
													y:
														(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 80) - 0 - 54) /
																2) +
														0 +
														15,
												},
												zB6OLzsMr: {
													height: 24,
													width: "24px",
													y: (componentViewport?.y || 0) + 13 + 0 + 0 + 15,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-iuq3fa-container"}
											layoutDependency={layoutDependency}
											layoutId={"XbhpJ8UuG-container"}
											nodeId={"XbhpJ8UuG"}
											rendersWithMotion={true}
											scopeId={"dZlNTDru2"}
										>
											{_jsx5(stdin_default2, {
												height: "100%",
												id: "XbhpJ8UuG",
												layoutId: "XbhpJ8UuG",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: "RYIK1jVXm",
												width: "100%",
												...addPropertyOverrides4(
													{
														IXlphbIvm: {
															XPTlw43ck: XPTlw43ck1vz6xnz,
														},
														zB6OLzsMr: {
															variant: "HYqfBQCDM",
															XPTlw43ck: XPTlw43ck2x5569,
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</motion4.div>
							{isDisplayed2() && (
								<motion4.div
									className={"framer-13al2pt"}
									data-framer-name={"Menu"}
									layoutDependency={layoutDependency}
									layoutId={"QlpEKL4BE"}
								>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "augiA20Il",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "augiA20Il",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "augiA20Il",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={32}
												y={
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 80) - 0 - 54) / 2) +
													9 +
													2
												}
												{...addPropertyOverrides4(
													{
														zB6OLzsMr: {
															y:
																(componentViewport?.y || 0) +
																13 +
																0 +
																78 +
																0 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-31hn6n-container"}
													layoutDependency={layoutDependency}
													layoutId={"v2okjTvWd-container"}
													nodeId={"v2okjTvWd"}
													rendersWithMotion={true}
													scopeId={"dZlNTDru2"}
												>
													{_jsx5(stdin_default3, {
														height: "100%",
														id: "v2okjTvWd",
														layoutId: "v2okjTvWd",
														o44erva5E: "Home",
														rS0NYgfTL: resolvedLinks[0],
														style: {
															height: "100%",
														},
														variant: "V_9sojbwT",
														width: "100%",
														...addPropertyOverrides4(
															{
																DlFmeIds8: {
																	rS0NYgfTL: resolvedLinks[1],
																},
																zB6OLzsMr: {
																	dAlYioEwr: dAlYioEwr2x5569,
																	rS0NYgfTL: resolvedLinks[2],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													pathVariables: {
														yzDdksNec: "full-menu",
													},
													unresolvedPathSlugs: {
														yzDdksNec: {
															collectionId: "M5XiN7F5c",
															collectionItemId: "bEeXsnV7c",
														},
													},
													webPageId: "cp2rlfnoU",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													pathVariables: {
														yzDdksNec: "full-menu",
													},
													unresolvedPathSlugs: {
														yzDdksNec: {
															collectionId: "M5XiN7F5c",
															collectionItemId: "bEeXsnV7c",
														},
													},
													webPageId: "cp2rlfnoU",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													pathVariables: {
														yzDdksNec: "full-menu",
													},
													unresolvedPathSlugs: {
														yzDdksNec: {
															collectionId: "M5XiN7F5c",
															collectionItemId: "bEeXsnV7c",
														},
													},
													webPageId: "cp2rlfnoU",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks1) => (
											<ComponentViewportProvider
												height={32}
												y={
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 80) - 0 - 54) / 2) +
													9 +
													2
												}
												{...addPropertyOverrides4(
													{
														zB6OLzsMr: {
															y:
																(componentViewport?.y || 0) +
																13 +
																0 +
																78 +
																0 +
																56,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-hq5fs1-container"}
													layoutDependency={layoutDependency}
													layoutId={"eJHC9Yycd-container"}
													nodeId={"eJHC9Yycd"}
													rendersWithMotion={true}
													scopeId={"dZlNTDru2"}
												>
													{_jsx5(stdin_default3, {
														height: "100%",
														id: "eJHC9Yycd",
														layoutId: "eJHC9Yycd",
														o44erva5E: "Menu",
														rS0NYgfTL: resolvedLinks1[0],
														style: {
															height: "100%",
														},
														variant: "V_9sojbwT",
														width: "100%",
														...addPropertyOverrides4(
															{
																DlFmeIds8: {
																	rS0NYgfTL: resolvedLinks1[1],
																},
																zB6OLzsMr: {
																	dAlYioEwr: dAlYioEwr2x5569,
																	rS0NYgfTL: resolvedLinks1[2],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "JmDr9THJu",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "JmDr9THJu",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "JmDr9THJu",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks2) => (
											<ComponentViewportProvider
												height={32}
												y={
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 80) - 0 - 54) / 2) +
													9 +
													2
												}
												{...addPropertyOverrides4(
													{
														zB6OLzsMr: {
															y:
																(componentViewport?.y || 0) +
																13 +
																0 +
																78 +
																0 +
																112,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-bjmzv7-container"}
													layoutDependency={layoutDependency}
													layoutId={"tIk_FBaEx-container"}
													nodeId={"tIk_FBaEx"}
													rendersWithMotion={true}
													scopeId={"dZlNTDru2"}
												>
													{_jsx5(stdin_default3, {
														height: "100%",
														id: "tIk_FBaEx",
														layoutId: "tIk_FBaEx",
														o44erva5E: "Contact",
														rS0NYgfTL: resolvedLinks2[0],
														style: {
															height: "100%",
														},
														variant: "V_9sojbwT",
														width: "100%",
														...addPropertyOverrides4(
															{
																DlFmeIds8: {
																	rS0NYgfTL: resolvedLinks2[1],
																},
																zB6OLzsMr: {
																	dAlYioEwr: dAlYioEwr2x5569,
																	rS0NYgfTL: resolvedLinks2[2],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ComponentViewportProvider
										height={36}
										y={
											(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 80) - 0 - 54) / 2) +
											9 +
											0
										}
										{...addPropertyOverrides4(
											{
												zB6OLzsMr: {
													y:
														(componentViewport?.y || 0) + 13 + 0 + 78 + 0 + 168,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											className={"framer-1v5627w-container"}
											layoutDependency={layoutDependency}
											layoutId={"LxlX1TSu3-container"}
											nodeId={"LxlX1TSu3"}
											rendersWithMotion={true}
											scopeId={"dZlNTDru2"}
											{...addPropertyOverrides4(
												{
													zB6OLzsMr: {
														__framer__animate: {
															transition: transition22,
														},
														__framer__animateOnce: false,
														__framer__enter: animation2,
														__framer__styleAppearEffectEnabled: true,
														__framer__threshold: 0.5,
														__perspectiveFX: false,
														__smartComponentFX: true,
														__targetOpacity: 1,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											{_jsx5(stdin_default, {
												height: "100%",
												id: "LxlX1TSu3",
												layoutId: "LxlX1TSu3",
												lJNtxFrg5: "https://framer.link/ODWvs5x",
												O5tlPGRu3: "Remix for FREE",
												variant: "C8LcdsPcq",
												width: "100%",
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
								</motion4.div>
							)}
						</motion4.div>
					</motion4.nav>
				</Transition4>
			</Variants4>
		</LayoutGroup4>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QVcdd.framer-1oncth0, .framer-QVcdd .framer-1oncth0 { display: block; }",
	".framer-QVcdd.framer-pv0et4 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: 80px; justify-content: center; overflow: visible; padding: 0px 24px 0px 24px; position: relative; width: 1200px; }",
	".framer-QVcdd .framer-khgfmz-container { flex: none; height: auto; left: 50%; position: absolute; top: 49%; width: auto; z-index: 1; }",
	".framer-QVcdd .framer-3cyhl6 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-QVcdd .framer-1i58zly { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 163px; }",
	".framer-QVcdd .framer-ub547f-container, .framer-QVcdd .framer-1v5627w-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-QVcdd .framer-iuq3fa-container { flex: none; height: 24px; position: relative; width: 24px; z-index: 1; }",
	".framer-QVcdd .framer-13al2pt { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-QVcdd .framer-31hn6n-container, .framer-QVcdd .framer-hq5fs1-container, .framer-QVcdd .framer-bjmzv7-container { flex: none; height: 32px; position: relative; width: auto; }",
	".framer-QVcdd.framer-v-16mby3w.framer-pv0et4 { width: 810px; }",
	".framer-QVcdd.framer-v-10sgyh6.framer-pv0et4 { padding: 0px 16px 0px 16px; width: 390px; }",
	".framer-QVcdd.framer-v-10sgyh6 .framer-1i58zly { flex: 1 0 0px; width: 1px; }",
	".framer-QVcdd.framer-v-1ii5ebr.framer-pv0et4 { align-content: flex-start; align-items: flex-start; height: 1200px; padding: 13px 16px 20px 16px; width: 390px; }",
	".framer-QVcdd.framer-v-1ii5ebr .framer-khgfmz-container { order: 0; }",
	".framer-QVcdd.framer-v-1ii5ebr .framer-3cyhl6 { flex-direction: column; gap: 24px; justify-content: flex-start; order: 1; padding: 0px 0px 24px 0px; }",
	".framer-QVcdd.framer-v-1ii5ebr .framer-1i58zly { height: 54px; width: 100%; }",
	".framer-QVcdd.framer-v-1ii5ebr .framer-13al2pt { flex-direction: column; gap: 24px; }",
];
var FramerdZlNTDru2 = withCSS4(Component4, css5, "framer-QVcdd");
var stdin_default5 = FramerdZlNTDru2;
FramerdZlNTDru2.displayName = "Top Nav/Nav";
FramerdZlNTDru2.defaultProps = {
	height: 80,
	width: 1200,
};
addPropertyControls5(FramerdZlNTDru2, {
	variant: {
		options: ["MkphMAJee", "DlFmeIds8", "IXlphbIvm", "zB6OLzsMr"],
		optionTitles: [
			"Desktop",
			"Tablet",
			"Mobile - Default",
			"Mobile - Default - Open",
		],
		title: "Variant",
		type: ControlType5.Enum,
	},
});
addFonts4(
	FramerdZlNTDru2,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...StopScrollFonts,
		...TopNavLogoFonts,
		...TopNavHamburgerMenuFonts,
		...TopNavMenuLinkFonts,
		...ButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:top-nav/nav
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "DlFmeIds8",
	xl: "MkphMAJee",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a377177818209678b37adc5f263446ba17148664a97f412372f73ef06885d900"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a377177818209678b37adc5f263446ba17148664a97f412372f73ef06885d900"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var nav_default = ComponentWithRoot;
export { nav_default as default };
